Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd,cwd+'/include',cwd+'/include/liblc3']

objs = DefineGroup('zbt', src, depend = ['ZBT'], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))    

Return('objs')
