Import('RTT_ROOT')
Import('rtconfig')
from building import *

src = []
cwd = GetCurrentDir()
CPPPATH = [cwd]
libpath = [cwd]
libs = []
if GetDepend('PKG_USING_ANYKA') and GetDepend('BF0_HCPU'):
    src = Glob('*.c')
    libs = ['libakaudiofilter']
group = DefineGroup('audio', src,depend = ['PKG_USING_ANYKA'],CPPPATH = CPPPATH, LIBS=libs, LIBPATH=libpath)

Return('group')
