/*
 * SPDX-FileCopyrightText: 2021-2025 SiFli Technologies(Nanjing) Co., Ltd
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef __BLE_NVDS_SERVICE_H
#define __BLE_NVDS_SERVICE_H
#include "data_service.h"

typedef enum
{
    BLE_NVDS_SERVICE_READ = MSG_SERVICE_CUSTOM_ID_BEGIN,
    BLE_NVDS_SERVICE_READ_TAG,
    BLE_NVDS_SERVICE_WRITE,
    BLE_NVDS_SERVICE_WRITE_TAG,
    BLE_NVDS_SERVICE_FLUSH,
    BLE_NVDS_SERVICE_UPDATE_ADDR,

    /* Response. */
    BLE_NVDS_SERVICE_READ_RSP = BLE_NVDS_SERVICE_READ | RSP_MSG_TYPE,
    BLE_NVDS_SERVICE_READ_TAG_RSP = BLE_NVDS_SERVICE_READ_TAG | RSP_MSG_TYPE,
    BLE_NVDS_SERVICE_WRITE_RSP = BLE_NVDS_SERVICE_WRITE | RSP_MSG_TYPE,
    BLE_NVDS_SERVICE_WRITE_TAG_RSP = BLE_NVDS_SERVICE_WRITE_TAG | RSP_MSG_TYPE,
    BLE_NVDS_SERVICE_FLUSH_COMPLETED = BLE_NVDS_SERVICE_FLUSH | RSP_MSG_TYPE,
    BLE_NVDS_SERVICE_UPDATE_ADDR_RSP = BLE_NVDS_SERVICE_UPDATE_ADDR | RSP_MSG_TYPE
} ble_nvds_service_message_t;

uint8_t ble_nvds_read_mac_address(uint8_t *addr, uint8_t len);

#endif // __BLE_NVDS_SERVICE_H


