#ifndef ZEPHYR_RTT_H
#define ZEPHYR_RTT_H
//BAP_BROADCAST_16_2_1
#ifdef BAP_BROADCAST_16_2_1
    #define CONFIG_BAP_BROADCAST_16_2_1 BAP_BROADCAST_16_2_1
#endif

//BAP_BROADCAST_24_2_1
#ifdef BAP_BROADCAST_24_2_1
    #define CONFIG_BAP_BROADCAST_24_2_1 BAP_BROADCAST_24_2_1
#endif

//BROADCAST_CODE
#ifdef BROADCAST_CODE
    #define CONFIG_BROADCAST_CODE BROADCAST_CODE
#endif

//BT_AICS
#ifdef BT_AICS
    #define CONFIG_BT_AICS BT_AICS
#endif

//BT_AICS_CLIENT_MAX_INSTANCE_COUNT
#ifdef BT_AICS_CLIENT_MAX_INSTANCE_COUNT
    #define CONFIG_BT_AICS_CLIENT_MAX_INSTANCE_COUNT BT_AICS_CLIENT_MAX_INSTANCE_COUNT
#endif

//BT_AICS_MAX_INPUT_DESCRIPTION_SIZE
#ifdef BT_AICS_MAX_INPUT_DESCRIPTION_SIZE
    #define CONFIG_BT_AICS_MAX_INPUT_DESCRIPTION_SIZE BT_AICS_MAX_INPUT_DESCRIPTION_SIZE
#endif

//BT_AICS_MAX_INSTANCE_COUNT
#ifdef BT_AICS_MAX_INSTANCE_COUNT
    #define CONFIG_BT_AICS_MAX_INSTANCE_COUNT BT_AICS_MAX_INSTANCE_COUNT
#endif

//BT_ASCS
#ifdef BT_ASCS
    #define CONFIG_BT_ASCS BT_ASCS
#endif

//BT_ASCS_ASE_BUF_TIMEOUT
#ifdef BT_ASCS_ASE_BUF_TIMEOUT
    #define CONFIG_BT_ASCS_ASE_BUF_TIMEOUT BT_ASCS_ASE_BUF_TIMEOUT
#endif

//BT_ASCS_ASE_SNK
#ifdef BT_ASCS_ASE_SNK
    #define CONFIG_BT_ASCS_ASE_SNK BT_ASCS_ASE_SNK
#endif

//BT_ASCS_ASE_SRC
#ifdef BT_ASCS_ASE_SRC
    #define CONFIG_BT_ASCS_ASE_SRC BT_ASCS_ASE_SRC
#endif

//BT_ASCS_ISO_DISCONNECT_DELAY
#ifdef BT_ASCS_ISO_DISCONNECT_DELAY
    #define CONFIG_BT_ASCS_ISO_DISCONNECT_DELAY BT_ASCS_ISO_DISCONNECT_DELAY
#endif

//BT_ASCS_MAX_ACTIVE_ASES
#ifdef BT_ASCS_MAX_ACTIVE_ASES
    #define CONFIG_BT_ASCS_MAX_ACTIVE_ASES BT_ASCS_MAX_ACTIVE_ASES
#endif

//BT_ASCS_MAX_ASE_SNK_COUNT
#ifdef BT_ASCS_MAX_ASE_SNK_COUNT
    #define CONFIG_BT_ASCS_MAX_ASE_SNK_COUNT BT_ASCS_MAX_ASE_SNK_COUNT
#endif

//BT_ASCS_MAX_ASE_SRC_COUNT
#ifdef BT_ASCS_MAX_ASE_SRC_COUNT
    #define CONFIG_BT_ASCS_MAX_ASE_SRC_COUNT BT_ASCS_MAX_ASE_SRC_COUNT
#endif

//BT_ASSERT
#ifdef BT_ASSERT
    #define CONFIG_BT_ASSERT BT_ASSERT
#endif

//BT_ASSERT_PANIC
#ifdef BT_ASSERT_PANIC
    #define CONFIG_BT_ASSERT_PANIC BT_ASSERT_PANIC
#endif

//BT_ASSERT_VERBOSE
#ifdef BT_ASSERT_VERBOSE
    #define CONFIG_BT_ASSERT_VERBOSE BT_ASSERT_VERBOSE
#endif

//BT_ATT_ERR_TO_STR
#ifdef BT_ATT_ERR_TO_STR
    #define CONFIG_BT_ATT_ERR_TO_STR BT_ATT_ERR_TO_STR
#endif

//BT_ATT_PREPARE_COUNT
#ifdef BT_ATT_PREPARE_COUNT
    #define CONFIG_BT_ATT_PREPARE_COUNT BT_ATT_PREPARE_COUNT
#endif

//BT_ATT_RETRY_ON_SEC_ERR
#ifdef BT_ATT_RETRY_ON_SEC_ERR
    #define CONFIG_BT_ATT_RETRY_ON_SEC_ERR BT_ATT_RETRY_ON_SEC_ERR
#endif

//BT_ATT_TX_COUNT
#ifdef BT_ATT_TX_COUNT
    #define CONFIG_BT_ATT_TX_COUNT BT_ATT_TX_COUNT
#endif

//BT_AUDIO
#ifdef BT_AUDIO
    #define CONFIG_BT_AUDIO BT_AUDIO
#endif

//BT_AUDIO_CODEC_CAP_MAX_DATA_SIZE
#ifdef BT_AUDIO_CODEC_CAP_MAX_DATA_SIZE
    #define CONFIG_BT_AUDIO_CODEC_CAP_MAX_DATA_SIZE BT_AUDIO_CODEC_CAP_MAX_DATA_SIZE
#endif

//BT_AUDIO_CODEC_CAP_MAX_METADATA_SIZE
#ifdef BT_AUDIO_CODEC_CAP_MAX_METADATA_SIZE
    #define CONFIG_BT_AUDIO_CODEC_CAP_MAX_METADATA_SIZE BT_AUDIO_CODEC_CAP_MAX_METADATA_SIZE
#endif

//BT_AUDIO_CODEC_CFG_MAX_DATA_SIZE
#ifdef BT_AUDIO_CODEC_CFG_MAX_DATA_SIZE
    #define CONFIG_BT_AUDIO_CODEC_CFG_MAX_DATA_SIZE BT_AUDIO_CODEC_CFG_MAX_DATA_SIZE
#endif

//BT_AUDIO_CODEC_CFG_MAX_METADATA_SIZE
#ifdef BT_AUDIO_CODEC_CFG_MAX_METADATA_SIZE
    #define CONFIG_BT_AUDIO_CODEC_CFG_MAX_METADATA_SIZE BT_AUDIO_CODEC_CFG_MAX_METADATA_SIZE
#endif

//BT_AUDIO_NOTIFY_RETRY_DELAY
#ifdef BT_AUDIO_NOTIFY_RETRY_DELAY
    #define CONFIG_BT_AUDIO_NOTIFY_RETRY_DELAY BT_AUDIO_NOTIFY_RETRY_DELAY
#endif

//BT_AUDIO_RX
#ifdef BT_AUDIO_RX
    #define CONFIG_BT_AUDIO_RX BT_AUDIO_RX
#endif

//BT_AUDIO_TX
#ifdef BT_AUDIO_TX
    #define CONFIG_BT_AUDIO_TX BT_AUDIO_TX
#endif

//BT_AUTO_DATA_LEN_UPDATE
#ifdef BT_AUTO_DATA_LEN_UPDATE
    #define CONFIG_BT_AUTO_DATA_LEN_UPDATE BT_AUTO_DATA_LEN_UPDATE
#endif

//BT_AUTO_PHY_UPDATE
#ifdef BT_AUTO_PHY_UPDATE
    #define CONFIG_BT_AUTO_PHY_UPDATE BT_AUTO_PHY_UPDATE
#endif

//BT_BACKGROUND_SCAN_INTERVAL
#ifdef BT_BACKGROUND_SCAN_INTERVAL
    #define CONFIG_BT_BACKGROUND_SCAN_INTERVAL BT_BACKGROUND_SCAN_INTERVAL
#endif

//BT_BACKGROUND_SCAN_WINDOW
#ifdef BT_BACKGROUND_SCAN_WINDOW
    #define CONFIG_BT_BACKGROUND_SCAN_WINDOW BT_BACKGROUND_SCAN_WINDOW
#endif

//BT_BAP_BASE
#ifdef BT_BAP_BASE
    #define CONFIG_BT_BAP_BASE BT_BAP_BASE
#endif

//BT_BAP_BASS_MAX_SUBGROUPS
#ifdef BT_BAP_BASS_MAX_SUBGROUPS
    #define CONFIG_BT_BAP_BASS_MAX_SUBGROUPS BT_BAP_BASS_MAX_SUBGROUPS
#endif

//BT_BAP_BROADCAST_ASSISTANT
#ifdef BT_BAP_BROADCAST_ASSISTANT
    #define CONFIG_BT_BAP_BROADCAST_ASSISTANT BT_BAP_BROADCAST_ASSISTANT
#endif

//BT_BAP_BROADCAST_ASSISTANT_RECV_STATE_COUNT
#ifdef BT_BAP_BROADCAST_ASSISTANT_RECV_STATE_COUNT
    #define CONFIG_BT_BAP_BROADCAST_ASSISTANT_RECV_STATE_COUNT BT_BAP_BROADCAST_ASSISTANT_RECV_STATE_COUNT
#endif

//BT_BAP_BROADCAST_SINK
#ifdef BT_BAP_BROADCAST_SINK
    #define CONFIG_BT_BAP_BROADCAST_SINK BT_BAP_BROADCAST_SINK
#endif

//BT_BAP_BROADCAST_SNK_COUNT
#ifdef BT_BAP_BROADCAST_SNK_COUNT
    #define CONFIG_BT_BAP_BROADCAST_SNK_COUNT BT_BAP_BROADCAST_SNK_COUNT
#endif

//BT_BAP_BROADCAST_SNK_STREAM_COUNT
#ifdef BT_BAP_BROADCAST_SNK_STREAM_COUNT
    #define CONFIG_BT_BAP_BROADCAST_SNK_STREAM_COUNT BT_BAP_BROADCAST_SNK_STREAM_COUNT
#endif

//BT_BAP_BROADCAST_SNK_SUBGROUP_COUNT
#ifdef BT_BAP_BROADCAST_SNK_SUBGROUP_COUNT
    #define CONFIG_BT_BAP_BROADCAST_SNK_SUBGROUP_COUNT BT_BAP_BROADCAST_SNK_SUBGROUP_COUNT
#endif

//BT_BAP_BROADCAST_SOURCE
#ifdef BT_BAP_BROADCAST_SOURCE
    #define CONFIG_BT_BAP_BROADCAST_SOURCE BT_BAP_BROADCAST_SOURCE
#endif

//BT_BAP_BROADCAST_SRC_COUNT
#ifdef BT_BAP_BROADCAST_SRC_COUNT
    #define CONFIG_BT_BAP_BROADCAST_SRC_COUNT BT_BAP_BROADCAST_SRC_COUNT
#endif

//BT_BAP_BROADCAST_SRC_STREAM_COUNT
#ifdef BT_BAP_BROADCAST_SRC_STREAM_COUNT
    #define CONFIG_BT_BAP_BROADCAST_SRC_STREAM_COUNT BT_BAP_BROADCAST_SRC_STREAM_COUNT
#endif

//BT_BAP_BROADCAST_SRC_SUBGROUP_COUNT
#ifdef BT_BAP_BROADCAST_SRC_SUBGROUP_COUNT
    #define CONFIG_BT_BAP_BROADCAST_SRC_SUBGROUP_COUNT BT_BAP_BROADCAST_SRC_SUBGROUP_COUNT
#endif

//BT_BAP_SCAN_DELEGATOR
#ifdef BT_BAP_SCAN_DELEGATOR
    #define CONFIG_BT_BAP_SCAN_DELEGATOR BT_BAP_SCAN_DELEGATOR
#endif

//BT_BAP_SCAN_DELEGATOR_BUF_TIMEOUT
#ifdef BT_BAP_SCAN_DELEGATOR_BUF_TIMEOUT
    #define CONFIG_BT_BAP_SCAN_DELEGATOR_BUF_TIMEOUT BT_BAP_SCAN_DELEGATOR_BUF_TIMEOUT
#endif

//BT_BAP_SCAN_DELEGATOR_RECV_STATE_COUNT
#ifdef BT_BAP_SCAN_DELEGATOR_RECV_STATE_COUNT
    #define CONFIG_BT_BAP_SCAN_DELEGATOR_RECV_STATE_COUNT BT_BAP_SCAN_DELEGATOR_RECV_STATE_COUNT
#endif

//BT_BAP_STREAM
#ifdef BT_BAP_STREAM
    #define CONFIG_BT_BAP_STREAM BT_BAP_STREAM
#endif

//BT_BAP_UNICAST
#ifdef BT_BAP_UNICAST
    #define CONFIG_BT_BAP_UNICAST BT_BAP_UNICAST
#endif

//BT_BAP_UNICAST_CLIENT
#ifdef BT_BAP_UNICAST_CLIENT
    #define CONFIG_BT_BAP_UNICAST_CLIENT BT_BAP_UNICAST_CLIENT
#endif

//BT_BAP_UNICAST_CLIENT_ASE_SNK
#ifdef BT_BAP_UNICAST_CLIENT_ASE_SNK
    #define CONFIG_BT_BAP_UNICAST_CLIENT_ASE_SNK BT_BAP_UNICAST_CLIENT_ASE_SNK
#endif

//BT_BAP_UNICAST_CLIENT_ASE_SNK_COUNT
#ifdef BT_BAP_UNICAST_CLIENT_ASE_SNK_COUNT
    #define CONFIG_BT_BAP_UNICAST_CLIENT_ASE_SNK_COUNT BT_BAP_UNICAST_CLIENT_ASE_SNK_COUNT
#endif

//BT_BAP_UNICAST_CLIENT_ASE_SRC
#ifdef BT_BAP_UNICAST_CLIENT_ASE_SRC
    #define CONFIG_BT_BAP_UNICAST_CLIENT_ASE_SRC BT_BAP_UNICAST_CLIENT_ASE_SRC
#endif

//BT_BAP_UNICAST_CLIENT_ASE_SRC_COUNT
#ifdef BT_BAP_UNICAST_CLIENT_ASE_SRC_COUNT
    #define CONFIG_BT_BAP_UNICAST_CLIENT_ASE_SRC_COUNT BT_BAP_UNICAST_CLIENT_ASE_SRC_COUNT
#endif

//BT_BAP_UNICAST_CLIENT_GROUP_COUNT
#ifdef BT_BAP_UNICAST_CLIENT_GROUP_COUNT
    #define CONFIG_BT_BAP_UNICAST_CLIENT_GROUP_COUNT BT_BAP_UNICAST_CLIENT_GROUP_COUNT
#endif

//BT_BAP_UNICAST_CLIENT_GROUP_STREAM_COUNT
#ifdef BT_BAP_UNICAST_CLIENT_GROUP_STREAM_COUNT
    #define CONFIG_BT_BAP_UNICAST_CLIENT_GROUP_STREAM_COUNT BT_BAP_UNICAST_CLIENT_GROUP_STREAM_COUNT
#endif

//BT_BAP_UNICAST_SERVER
#ifdef BT_BAP_UNICAST_SERVER
    #define CONFIG_BT_BAP_UNICAST_SERVER BT_BAP_UNICAST_SERVER
#endif

//BT_BAS
#ifdef BT_BAS
    #define CONFIG_BT_BAS BT_BAS
#endif

//BT_BAS_BLS
#ifdef BT_BAS_BLS
    #define CONFIG_BT_BAS_BLS BT_BAS_BLS
#endif

//BT_BAS_BLS_ADDITIONAL_STATUS_PRESENT
#ifdef BT_BAS_BLS_ADDITIONAL_STATUS_PRESENT
    #define CONFIG_BT_BAS_BLS_ADDITIONAL_STATUS_PRESENT BT_BAS_BLS_ADDITIONAL_STATUS_PRESENT
#endif

//BT_BAS_BLS_BATTERY_LEVEL_PRESENT
#ifdef BT_BAS_BLS_BATTERY_LEVEL_PRESENT
    #define CONFIG_BT_BAS_BLS_BATTERY_LEVEL_PRESENT BT_BAS_BLS_BATTERY_LEVEL_PRESENT
#endif

//BT_BAS_BLS_IDENTIFIER_PRESENT
#ifdef BT_BAS_BLS_IDENTIFIER_PRESENT
    #define CONFIG_BT_BAS_BLS_IDENTIFIER_PRESENT BT_BAS_BLS_IDENTIFIER_PRESENT
#endif

//BT_BONDABLE
#ifdef BT_BONDABLE
    #define CONFIG_BT_BONDABLE BT_BONDABLE
#endif

//BT_BONDABLE_PER_CONNECTION
#ifdef BT_BONDABLE_PER_CONNECTION
    #define CONFIG_BT_BONDABLE_PER_CONNECTION BT_BONDABLE_PER_CONNECTION
#endif

//BT_BONDING_REQUIRED
#ifdef BT_BONDING_REQUIRED
    #define CONFIG_BT_BONDING_REQUIRED BT_BONDING_REQUIRED
#endif

//BT_BROADCASTER
#ifdef BT_BROADCASTER
    #define CONFIG_BT_BROADCASTER BT_BROADCASTER
#endif

//BT_BUF_ACL_RX_COUNT
#ifdef BT_BUF_ACL_RX_COUNT
    #define CONFIG_BT_BUF_ACL_RX_COUNT BT_BUF_ACL_RX_COUNT
#endif

//BT_BUF_ACL_RX_SIZE
#ifdef BT_BUF_ACL_RX_SIZE
    #define CONFIG_BT_BUF_ACL_RX_SIZE BT_BUF_ACL_RX_SIZE
#endif

//BT_BUF_ACL_TX_COUNT
#ifdef BT_BUF_ACL_TX_COUNT
    #define CONFIG_BT_BUF_ACL_TX_COUNT BT_BUF_ACL_TX_COUNT
#endif

//BT_BUF_ACL_TX_SIZE
#ifdef BT_BUF_ACL_TX_SIZE
    #define CONFIG_BT_BUF_ACL_TX_SIZE BT_BUF_ACL_TX_SIZE
#endif

//BT_BUF_CMD_TX_COUNT
#ifdef BT_BUF_CMD_TX_COUNT
    #define CONFIG_BT_BUF_CMD_TX_COUNT BT_BUF_CMD_TX_COUNT
#endif

//BT_BUF_CMD_TX_SIZE2
#ifdef BT_BUF_CMD_TX_SIZE2
    #define CONFIG_BT_BUF_CMD_TX_SIZE BT_BUF_CMD_TX_SIZE2
#endif

//BT_BUF_EVT_DISCARDABLE_COUNT
#ifdef BT_BUF_EVT_DISCARDABLE_COUNT
    #define CONFIG_BT_BUF_EVT_DISCARDABLE_COUNT BT_BUF_EVT_DISCARDABLE_COUNT
#endif

//BT_BUF_EVT_DISCARDABLE_SIZE
#ifdef BT_BUF_EVT_DISCARDABLE_SIZE
    #define CONFIG_BT_BUF_EVT_DISCARDABLE_SIZE BT_BUF_EVT_DISCARDABLE_SIZE
#endif

//BT_BUF_EVT_RX_COUNT
#ifdef BT_BUF_EVT_RX_COUNT
    #define CONFIG_BT_BUF_EVT_RX_COUNT BT_BUF_EVT_RX_COUNT
#endif

//BT_BUF_EVT_RX_SIZE2
#ifdef BT_BUF_EVT_RX_SIZE2
    #define CONFIG_BT_BUF_EVT_RX_SIZE BT_BUF_EVT_RX_SIZE2
#endif

//BT_CAP
#ifdef BT_CAP
    #define CONFIG_BT_CAP BT_CAP
#endif

//BT_CAP_ACCEPTOR
#ifdef BT_CAP_ACCEPTOR
    #define CONFIG_BT_CAP_ACCEPTOR BT_CAP_ACCEPTOR
#endif

//BT_CAP_ACCEPTOR_SET_MEMBER
#ifdef BT_CAP_ACCEPTOR_SET_MEMBER
    #define CONFIG_BT_CAP_ACCEPTOR_SET_MEMBER BT_CAP_ACCEPTOR_SET_MEMBER
#endif

//BT_CAP_COMMANDER
#ifdef BT_CAP_COMMANDER
    #define CONFIG_BT_CAP_COMMANDER BT_CAP_COMMANDER
#endif

//BT_CAP_INITIATOR
#ifdef BT_CAP_INITIATOR
    #define CONFIG_BT_CAP_INITIATOR BT_CAP_INITIATOR
#endif

//BT_CAP_INITIATOR_UNICAST
#ifdef BT_CAP_INITIATOR_UNICAST
    #define CONFIG_BT_CAP_INITIATOR_UNICAST BT_CAP_INITIATOR_UNICAST
#endif

//BT_CCP_CALL_CONTROL_CLIENT
#ifdef BT_CCP_CALL_CONTROL_CLIENT
    #define CONFIG_BT_CCP_CALL_CONTROL_CLIENT BT_CCP_CALL_CONTROL_CLIENT
#endif

//BT_CCP_CALL_CONTROL_CLIENT_BEARER_COUNT
#ifdef BT_CCP_CALL_CONTROL_CLIENT_BEARER_COUNT
    #define CONFIG_BT_CCP_CALL_CONTROL_CLIENT_BEARER_COUNT BT_CCP_CALL_CONTROL_CLIENT_BEARER_COUNT
#endif

//BT_CCP_CALL_CONTROL_SERVER
#ifdef BT_CCP_CALL_CONTROL_SERVER
    #define CONFIG_BT_CCP_CALL_CONTROL_SERVER BT_CCP_CALL_CONTROL_SERVER
#endif

//BT_CCP_CALL_CONTROL_SERVER_BEARER_COUNT
#ifdef BT_CCP_CALL_CONTROL_SERVER_BEARER_COUNT
    #define CONFIG_BT_CCP_CALL_CONTROL_SERVER_BEARER_COUNT BT_CCP_CALL_CONTROL_SERVER_BEARER_COUNT
#endif

//BT_CENTRAL
#ifdef BT_CENTRAL
    #define CONFIG_BT_CENTRAL BT_CENTRAL
#endif

//BT_CHANNEL_SOUNDING
#ifdef BT_CHANNEL_SOUNDING
    #define CONFIG_BT_CHANNEL_SOUNDING BT_CHANNEL_SOUNDING
#endif

//BT_CLASSIC
#ifdef BT_CLASSIC
    #define CONFIG_BT_CLASSIC BT_CLASSIC
#endif

//BT_COMPANY_ID
#ifdef BT_COMPANY_ID
    #define CONFIG_BT_COMPANY_ID BT_COMPANY_ID
#endif

//BT_CONN
#ifdef BT_CONN
    #define CONFIG_BT_CONN BT_CONN
#endif

//BT_CONN_CHECK_NULL_BEFORE_CREATE
#ifdef BT_CONN_CHECK_NULL_BEFORE_CREATE
    #define CONFIG_BT_CONN_CHECK_NULL_BEFORE_CREATE BT_CONN_CHECK_NULL_BEFORE_CREATE
#endif

//BT_CONN_FRAG_COUNT
#ifdef BT_CONN_FRAG_COUNT
    #define CONFIG_BT_CONN_FRAG_COUNT BT_CONN_FRAG_COUNT
#endif

//BT_CONN_PARAM_ANY
#ifdef BT_CONN_PARAM_ANY
    #define CONFIG_BT_CONN_PARAM_ANY BT_CONN_PARAM_ANY
#endif

//BT_CONN_PARAM_RETRY_COUNT
#ifdef BT_CONN_PARAM_RETRY_COUNT
    #define CONFIG_BT_CONN_PARAM_RETRY_COUNT BT_CONN_PARAM_RETRY_COUNT
#endif

//BT_CONN_PARAM_RETRY_TIMEOUT
#ifdef BT_CONN_PARAM_RETRY_TIMEOUT
    #define CONFIG_BT_CONN_PARAM_RETRY_TIMEOUT BT_CONN_PARAM_RETRY_TIMEOUT
#endif

//BT_CONN_PARAM_UPDATE_TIMEOUT
#ifdef BT_CONN_PARAM_UPDATE_TIMEOUT
    #define CONFIG_BT_CONN_PARAM_UPDATE_TIMEOUT BT_CONN_PARAM_UPDATE_TIMEOUT
#endif

//BT_CONN_TX
#ifdef BT_CONN_TX
    #define CONFIG_BT_CONN_TX BT_CONN_TX
#endif

//BT_CONN_TX_MAX
#ifdef BT_CONN_TX_MAX
    #define CONFIG_BT_CONN_TX_MAX BT_CONN_TX_MAX
#endif

//BT_CONN_TX_NOTIFY_WQ
#ifdef BT_CONN_TX_NOTIFY_WQ
    #define CONFIG_BT_CONN_TX_NOTIFY_WQ BT_CONN_TX_NOTIFY_WQ
#endif

//BT_CONN_TX_USER_DATA_SIZE
#ifdef BT_CONN_TX_USER_DATA_SIZE
    #define CONFIG_BT_CONN_TX_USER_DATA_SIZE BT_CONN_TX_USER_DATA_SIZE
#endif

//BT_CREATE_CONN_TIMEOUT
#ifdef BT_CREATE_CONN_TIMEOUT
    #define CONFIG_BT_CREATE_CONN_TIMEOUT BT_CREATE_CONN_TIMEOUT
#endif

//BT_CSIP_SET_COORDINATOR
#ifdef BT_CSIP_SET_COORDINATOR
    #define CONFIG_BT_CSIP_SET_COORDINATOR BT_CSIP_SET_COORDINATOR
#endif

//BT_CSIP_SET_COORDINATOR_ENC_SIRK_SUPPORT
#ifdef BT_CSIP_SET_COORDINATOR_ENC_SIRK_SUPPORT
    #define CONFIG_BT_CSIP_SET_COORDINATOR_ENC_SIRK_SUPPORT BT_CSIP_SET_COORDINATOR_ENC_SIRK_SUPPORT
#endif

//BT_CSIP_SET_COORDINATOR_MAX_CSIS_INSTANCES
#ifdef BT_CSIP_SET_COORDINATOR_MAX_CSIS_INSTANCES
    #define CONFIG_BT_CSIP_SET_COORDINATOR_MAX_CSIS_INSTANCES BT_CSIP_SET_COORDINATOR_MAX_CSIS_INSTANCES
#endif

//BT_CSIP_SET_COORDINATOR_TEST_SAMPLE_DATA
#ifdef BT_CSIP_SET_COORDINATOR_TEST_SAMPLE_DATA
    #define CONFIG_BT_CSIP_SET_COORDINATOR_TEST_SAMPLE_DATA BT_CSIP_SET_COORDINATOR_TEST_SAMPLE_DATA
#endif

//BT_CSIP_SET_MEMBER
#ifdef BT_CSIP_SET_MEMBER
    #define CONFIG_BT_CSIP_SET_MEMBER BT_CSIP_SET_MEMBER
#endif

//BT_CSIP_SET_MEMBER_ENC_SIRK_SUPPORT
#ifdef BT_CSIP_SET_MEMBER_ENC_SIRK_SUPPORT
    #define CONFIG_BT_CSIP_SET_MEMBER_ENC_SIRK_SUPPORT BT_CSIP_SET_MEMBER_ENC_SIRK_SUPPORT
#endif

//BT_CSIP_SET_MEMBER_MAX_INSTANCE_COUNT
#ifdef BT_CSIP_SET_MEMBER_MAX_INSTANCE_COUNT
    #define CONFIG_BT_CSIP_SET_MEMBER_MAX_INSTANCE_COUNT BT_CSIP_SET_MEMBER_MAX_INSTANCE_COUNT
#endif

//BT_CSIP_SET_MEMBER_NOTIFIABLE
#ifdef BT_CSIP_SET_MEMBER_NOTIFIABLE
    #define CONFIG_BT_CSIP_SET_MEMBER_NOTIFIABLE BT_CSIP_SET_MEMBER_NOTIFIABLE
#endif

//BT_CSIP_SET_MEMBER_TEST_SAMPLE_DATA
#ifdef BT_CSIP_SET_MEMBER_TEST_SAMPLE_DATA
    #define CONFIG_BT_CSIP_SET_MEMBER_TEST_SAMPLE_DATA BT_CSIP_SET_MEMBER_TEST_SAMPLE_DATA
#endif

//BT_CTLR_SCAN_DATA_LEN_MAX
#ifdef BT_CTLR_SCAN_DATA_LEN_MAX
    #define CONFIG_BT_CTLR_SCAN_DATA_LEN_MAX BT_CTLR_SCAN_DATA_LEN_MAX
#endif

//BT_CTS
#ifdef BT_CTS
    #define CONFIG_BT_CTS BT_CTS
#endif

//BT_CTS_HELPER_API
#ifdef BT_CTS_HELPER_API
    #define CONFIG_BT_CTS_HELPER_API BT_CTS_HELPER_API
#endif

//BT_CUSTOM
#ifdef BT_CUSTOM
    #define CONFIG_BT_CUSTOM BT_CUSTOM
#endif

//BT_DATA_LEN_UPDATE
#ifdef BT_DATA_LEN_UPDATE
    #define CONFIG_BT_DATA_LEN_UPDATE BT_DATA_LEN_UPDATE
#endif

//BT_DEBUG_MONITOR_UART
#ifdef BT_DEBUG_MONITOR_UART
    #define CONFIG_BT_DEBUG_MONITOR_UART BT_DEBUG_MONITOR_UART
#endif

//BT_DEBUG_NONE
#ifdef BT_DEBUG_NONE
    #define CONFIG_BT_DEBUG_NONE BT_DEBUG_NONE
#endif

//BT_DEVICE_APPEARANCE
#ifdef BT_DEVICE_APPEARANCE
    #define CONFIG_BT_DEVICE_APPEARANCE BT_DEVICE_APPEARANCE
#endif

//BT_DEVICE_APPEARANCE_DYNAMIC
#ifdef BT_DEVICE_APPEARANCE_DYNAMIC
    #define CONFIG_BT_DEVICE_APPEARANCE_DYNAMIC BT_DEVICE_APPEARANCE_DYNAMIC
#endif

//BT_DEVICE_NAME
#ifdef BT_DEVICE_NAME
    #define CONFIG_BT_DEVICE_NAME BT_DEVICE_NAME
#endif

//BT_DEVICE_NAME_DYNAMIC
#ifdef BT_DEVICE_NAME_DYNAMIC
    #define CONFIG_BT_DEVICE_NAME_DYNAMIC BT_DEVICE_NAME_DYNAMIC
#endif

//BT_DEVICE_NAME_GATT_WRITABLE
#ifdef BT_DEVICE_NAME_GATT_WRITABLE
    #define CONFIG_BT_DEVICE_NAME_GATT_WRITABLE BT_DEVICE_NAME_GATT_WRITABLE
#endif

//BT_DEVICE_NAME_MAX
#ifdef BT_DEVICE_NAME_MAX
    #define CONFIG_BT_DEVICE_NAME_MAX BT_DEVICE_NAME_MAX
#endif

//BT_DF
#ifdef BT_DF
    #define CONFIG_BT_DF BT_DF
#endif

//BT_DIS
#ifdef BT_DIS
    #define CONFIG_BT_DIS BT_DIS
#endif

//BT_DIS_FW_REV
#ifdef BT_DIS_FW_REV
    #define CONFIG_BT_DIS_FW_REV BT_DIS_FW_REV
#endif

//BT_DIS_FW_REV_STR
#ifdef BT_DIS_FW_REV_STR
    #define CONFIG_BT_DIS_FW_REV_STR BT_DIS_FW_REV_STR
#endif

//BT_DIS_HW_REV
#ifdef BT_DIS_HW_REV
    #define CONFIG_BT_DIS_HW_REV BT_DIS_HW_REV
#endif

//BT_DIS_HW_REV_STR
#ifdef BT_DIS_HW_REV_STR
    #define CONFIG_BT_DIS_HW_REV_STR BT_DIS_HW_REV_STR
#endif

//BT_DIS_IEEE_RCDL
#ifdef BT_DIS_IEEE_RCDL
    #define CONFIG_BT_DIS_IEEE_RCDL BT_DIS_IEEE_RCDL
#endif

//BT_DIS_MANUF
#ifdef BT_DIS_MANUF
    #define CONFIG_BT_DIS_MANUF BT_DIS_MANUF
#endif

//BT_DIS_MODEL
#ifdef BT_DIS_MODEL
    #define CONFIG_BT_DIS_MODEL BT_DIS_MODEL
#endif

//BT_DIS_PNP
#ifdef BT_DIS_PNP
    #define CONFIG_BT_DIS_PNP BT_DIS_PNP
#endif

//BT_DIS_PNP_PID
#ifdef BT_DIS_PNP_PID
    #define CONFIG_BT_DIS_PNP_PID BT_DIS_PNP_PID
#endif

//BT_DIS_PNP_VER
#ifdef BT_DIS_PNP_VER
    #define CONFIG_BT_DIS_PNP_VER BT_DIS_PNP_VER
#endif

//BT_DIS_PNP_VID
#ifdef BT_DIS_PNP_VID
    #define CONFIG_BT_DIS_PNP_VID BT_DIS_PNP_VID
#endif

//BT_DIS_PNP_VID_SRC
#ifdef BT_DIS_PNP_VID_SRC
    #define CONFIG_BT_DIS_PNP_VID_SRC BT_DIS_PNP_VID_SRC
#endif

//BT_DIS_SERIAL_NUMBER
#ifdef BT_DIS_SERIAL_NUMBER
    #define CONFIG_BT_DIS_SERIAL_NUMBER BT_DIS_SERIAL_NUMBER
#endif

//BT_DIS_SERIAL_NUMBER_STR
#ifdef BT_DIS_SERIAL_NUMBER_STR
    #define CONFIG_BT_DIS_SERIAL_NUMBER_STR BT_DIS_SERIAL_NUMBER_STR
#endif

//BT_DIS_SETTINGS
#ifdef BT_DIS_SETTINGS
    #define CONFIG_BT_DIS_SETTINGS BT_DIS_SETTINGS
#endif

//BT_DIS_STR_MAX
#ifdef BT_DIS_STR_MAX
    #define CONFIG_BT_DIS_STR_MAX BT_DIS_STR_MAX
#endif

//BT_DIS_SW_REV
#ifdef BT_DIS_SW_REV
    #define CONFIG_BT_DIS_SW_REV BT_DIS_SW_REV
#endif

//BT_DIS_SW_REV_STR
#ifdef BT_DIS_SW_REV_STR
    #define CONFIG_BT_DIS_SW_REV_STR BT_DIS_SW_REV_STR
#endif

//BT_DIS_SYSTEM_ID
#ifdef BT_DIS_SYSTEM_ID
    #define CONFIG_BT_DIS_SYSTEM_ID BT_DIS_SYSTEM_ID
#endif

//BT_DIS_UDI
#ifdef BT_DIS_UDI
    #define CONFIG_BT_DIS_UDI BT_DIS_UDI
#endif

//BT_DRIVER_RX_HIGH_PRIO
#ifdef BT_DRIVER_RX_HIGH_PRIO
    #define CONFIG_BT_DRIVER_RX_HIGH_PRIO BT_DRIVER_RX_HIGH_PRIO
#endif

//BT_EAD
#ifdef BT_EAD
    #define CONFIG_BT_EAD BT_EAD
#endif

//BT_ECC
#ifdef BT_ECC
    #define CONFIG_BT_ECC BT_ECC
#endif

//BT_EXT_ADV
#ifdef BT_EXT_ADV
    #define CONFIG_BT_EXT_ADV BT_EXT_ADV
#endif

//BT_EXT_ADV_LEGACY_SUPPORT
#ifdef BT_EXT_ADV_LEGACY_SUPPORT
    #define CONFIG_BT_EXT_ADV_LEGACY_SUPPORT BT_EXT_ADV_LEGACY_SUPPORT
#endif

//BT_EXT_ADV_MAX_ADV_SET
#ifdef BT_EXT_ADV_MAX_ADV_SET
    #define CONFIG_BT_EXT_ADV_MAX_ADV_SET BT_EXT_ADV_MAX_ADV_SET
#endif

//BT_EXT_SCAN_BUF_SIZE
#ifdef BT_EXT_SCAN_BUF_SIZE
    #define CONFIG_BT_EXT_SCAN_BUF_SIZE BT_EXT_SCAN_BUF_SIZE
#endif

//BT_FILTER_ACCEPT_LIST
#ifdef BT_FILTER_ACCEPT_LIST
    #define CONFIG_BT_FILTER_ACCEPT_LIST BT_FILTER_ACCEPT_LIST
#endif

//BT_FIXED_PASSKEY
#ifdef BT_FIXED_PASSKEY
    #define CONFIG_BT_FIXED_PASSKEY BT_FIXED_PASSKEY
#endif

//BT_GAP_AUTO_UPDATE_CONN_PARAMS
#ifdef BT_GAP_AUTO_UPDATE_CONN_PARAMS
    #define CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS BT_GAP_AUTO_UPDATE_CONN_PARAMS
#endif

//BT_GAP_PERIPHERAL_PREF_PARAMS
#ifdef BT_GAP_PERIPHERAL_PREF_PARAMS
    #define CONFIG_BT_GAP_PERIPHERAL_PREF_PARAMS BT_GAP_PERIPHERAL_PREF_PARAMS
#endif

//BT_GATT_AUTHORIZATION_CUSTOM
#ifdef BT_GATT_AUTHORIZATION_CUSTOM
    #define CONFIG_BT_GATT_AUTHORIZATION_CUSTOM BT_GATT_AUTHORIZATION_CUSTOM
#endif

//BT_GATT_AUTO_DISCOVER_CCC
#ifdef BT_GATT_AUTO_DISCOVER_CCC
    #define CONFIG_BT_GATT_AUTO_DISCOVER_CCC BT_GATT_AUTO_DISCOVER_CCC
#endif

//BT_GATT_AUTO_RESUBSCRIBE
#ifdef BT_GATT_AUTO_RESUBSCRIBE
    #define CONFIG_BT_GATT_AUTO_RESUBSCRIBE BT_GATT_AUTO_RESUBSCRIBE
#endif

//BT_GATT_AUTO_SEC_REQ
#ifdef BT_GATT_AUTO_SEC_REQ
    #define CONFIG_BT_GATT_AUTO_SEC_REQ BT_GATT_AUTO_SEC_REQ
#endif

//BT_GATT_AUTO_UPDATE_MTU
#ifdef BT_GATT_AUTO_UPDATE_MTU
    #define CONFIG_BT_GATT_AUTO_UPDATE_MTU BT_GATT_AUTO_UPDATE_MTU
#endif

//BT_GATT_CACHING
#ifdef BT_GATT_CACHING
    #define CONFIG_BT_GATT_CACHING BT_GATT_CACHING
#endif

//BT_GATT_CLIENT
#ifdef BT_GATT_CLIENT
    #define CONFIG_BT_GATT_CLIENT BT_GATT_CLIENT
#endif

//BT_GATT_DYNAMIC_DB
#ifdef BT_GATT_DYNAMIC_DB
    #define CONFIG_BT_GATT_DYNAMIC_DB BT_GATT_DYNAMIC_DB
#endif

//BT_GATT_ENFORCE_CHANGE_UNAWARE
#ifdef BT_GATT_ENFORCE_CHANGE_UNAWARE
    #define CONFIG_BT_GATT_ENFORCE_CHANGE_UNAWARE BT_GATT_ENFORCE_CHANGE_UNAWARE
#endif

//BT_GATT_ENFORCE_SUBSCRIPTION
#ifdef BT_GATT_ENFORCE_SUBSCRIPTION
    #define CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION BT_GATT_ENFORCE_SUBSCRIPTION
#endif

//BT_GATT_NOTIFY_MULTIPLE
#ifdef BT_GATT_NOTIFY_MULTIPLE
    #define CONFIG_BT_GATT_NOTIFY_MULTIPLE BT_GATT_NOTIFY_MULTIPLE
#endif

//BT_GATT_READ_MULTIPLE
#ifdef BT_GATT_READ_MULTIPLE
    #define CONFIG_BT_GATT_READ_MULTIPLE BT_GATT_READ_MULTIPLE
#endif

//BT_GATT_READ_MULT_VAR_LEN
#ifdef BT_GATT_READ_MULT_VAR_LEN
    #define CONFIG_BT_GATT_READ_MULT_VAR_LEN BT_GATT_READ_MULT_VAR_LEN
#endif

//BT_GATT_SERVICE_CHANGED
#ifdef BT_GATT_SERVICE_CHANGED
    #define CONFIG_BT_GATT_SERVICE_CHANGED BT_GATT_SERVICE_CHANGED
#endif

//BT_GMAP
#ifdef BT_GMAP
    #define CONFIG_BT_GMAP BT_GMAP
#endif

//BT_GMAP_UGG_SUPPORTED
#ifdef BT_GMAP_UGG_SUPPORTED
    #define CONFIG_BT_GMAP_UGG_SUPPORTED BT_GMAP_UGG_SUPPORTED
#endif

//BT_GMAP_UGT_SUPPORTED
#ifdef BT_GMAP_UGT_SUPPORTED
    #define CONFIG_BT_GMAP_UGT_SUPPORTED BT_GMAP_UGT_SUPPORTED
#endif

//BT_HAS
#ifdef BT_HAS
    #define CONFIG_BT_HAS BT_HAS
#endif

//BT_HAS_ACTIVE_PRESET_INDEX
#ifdef BT_HAS_ACTIVE_PRESET_INDEX
    #define CONFIG_BT_HAS_ACTIVE_PRESET_INDEX BT_HAS_ACTIVE_PRESET_INDEX
#endif

//BT_HAS_CLIENT
#ifdef BT_HAS_CLIENT
    #define CONFIG_BT_HAS_CLIENT BT_HAS_CLIENT
#endif

//BT_HAS_FEATURES_NOTIFIABLE
#ifdef BT_HAS_FEATURES_NOTIFIABLE
    #define CONFIG_BT_HAS_FEATURES_NOTIFIABLE BT_HAS_FEATURES_NOTIFIABLE
#endif

//BT_HAS_PRESET_COUNT
#ifdef BT_HAS_PRESET_COUNT
    #define CONFIG_BT_HAS_PRESET_COUNT BT_HAS_PRESET_COUNT
#endif

//BT_HAS_PRESET_NAME_DYNAMIC
#ifdef BT_HAS_PRESET_NAME_DYNAMIC
    #define CONFIG_BT_HAS_PRESET_NAME_DYNAMIC BT_HAS_PRESET_NAME_DYNAMIC
#endif

//BT_HAS_PRESET_SUPPORT
#ifdef BT_HAS_PRESET_SUPPORT
    #define CONFIG_BT_HAS_PRESET_SUPPORT BT_HAS_PRESET_SUPPORT
#endif

//BT_HCI
#ifdef BT_HCI
    #define CONFIG_BT_HCI BT_HCI
#endif

//BT_HCI_ACL_FLOW_CONTROL
#ifdef BT_HCI_ACL_FLOW_CONTROL
    #define CONFIG_BT_HCI_ACL_FLOW_CONTROL BT_HCI_ACL_FLOW_CONTROL
#endif

//BT_HCI_ERR_TO_STR
#ifdef BT_HCI_ERR_TO_STR
    #define CONFIG_BT_HCI_ERR_TO_STR BT_HCI_ERR_TO_STR
#endif

//BT_HCI_HOST
#ifdef BT_HCI_HOST
    #define CONFIG_BT_HCI_HOST BT_HCI_HOST
#endif

//BT_HCI_MESH_EXT
#ifdef BT_HCI_MESH_EXT
    #define CONFIG_BT_HCI_MESH_EXT BT_HCI_MESH_EXT
#endif

//BT_HCI_RAW
#ifdef BT_HCI_RAW
    #define CONFIG_BT_HCI_RAW BT_HCI_RAW
#endif

//BT_HCI_RAW_CMD_EXT
#ifdef BT_HCI_RAW_CMD_EXT
    #define CONFIG_BT_HCI_RAW_CMD_EXT BT_HCI_RAW_CMD_EXT
#endif

//BT_HCI_RAW_H4
#ifdef BT_HCI_RAW_H4
    #define CONFIG_BT_HCI_RAW_H4 BT_HCI_RAW_H4
#endif

//BT_HCI_SETUP
#ifdef BT_HCI_SETUP
    #define CONFIG_BT_HCI_SETUP BT_HCI_SETUP
#endif

//BT_HCI_SET_PUBLIC_ADDR
#ifdef BT_HCI_SET_PUBLIC_ADDR
    #define CONFIG_BT_HCI_SET_PUBLIC_ADDR BT_HCI_SET_PUBLIC_ADDR
#endif

//BT_HCI_TX_PRIO
#ifdef BT_HCI_TX_PRIO
    #define CONFIG_BT_HCI_TX_PRIO BT_HCI_TX_PRIO
#endif

//BT_HCI_TX_STACK_SIZE
#ifdef BT_HCI_TX_STACK_SIZE
    #define CONFIG_BT_HCI_TX_STACK_SIZE BT_HCI_TX_STACK_SIZE
#endif

//BT_HCI_TX_STACK_SIZE_WITH_PROMPT
#ifdef BT_HCI_TX_STACK_SIZE_WITH_PROMPT
    #define CONFIG_BT_HCI_TX_STACK_SIZE_WITH_PROMPT BT_HCI_TX_STACK_SIZE_WITH_PROMPT
#endif

//BT_HCI_VS
#ifdef BT_HCI_VS
    #define CONFIG_BT_HCI_VS BT_HCI_VS
#endif

//BT_HCI_VS_EVT_USER
#ifdef BT_HCI_VS_EVT_USER
    #define CONFIG_BT_HCI_VS_EVT_USER BT_HCI_VS_EVT_USER
#endif

//BT_HOST_CCM
#ifdef BT_HOST_CCM
    #define CONFIG_BT_HOST_CCM BT_HOST_CCM
#endif

//BT_HOST_CRYPTO
#ifdef BT_HOST_CRYPTO
    #define CONFIG_BT_HOST_CRYPTO BT_HOST_CRYPTO
#endif

//BT_HOST_CRYPTO_PRNG
#ifdef BT_HOST_CRYPTO_PRNG
    #define CONFIG_BT_HOST_CRYPTO_PRNG BT_HOST_CRYPTO_PRNG
#endif

//BT_HRS
#ifdef BT_HRS
    #define CONFIG_BT_HRS BT_HRS
#endif

//BT_HRS_DEFAULT_PERM_RW
#ifdef BT_HRS_DEFAULT_PERM_RW
    #define CONFIG_BT_HRS_DEFAULT_PERM_RW BT_HRS_DEFAULT_PERM_RW
#endif

//BT_HRS_DEFAULT_PERM_RW_AUTHEN
#ifdef BT_HRS_DEFAULT_PERM_RW_AUTHEN
    #define CONFIG_BT_HRS_DEFAULT_PERM_RW_AUTHEN BT_HRS_DEFAULT_PERM_RW_AUTHEN
#endif

//BT_HRS_DEFAULT_PERM_RW_ENCRYPT
#ifdef BT_HRS_DEFAULT_PERM_RW_ENCRYPT
    #define CONFIG_BT_HRS_DEFAULT_PERM_RW_ENCRYPT BT_HRS_DEFAULT_PERM_RW_ENCRYPT
#endif

//BT_IAS
#ifdef BT_IAS
    #define CONFIG_BT_IAS BT_IAS
#endif

//BT_IAS_CLIENT
#ifdef BT_IAS_CLIENT
    #define CONFIG_BT_IAS_CLIENT BT_IAS_CLIENT
#endif

//BT_IAS_SEC_AUTH
#ifdef BT_IAS_SEC_AUTH
    #define CONFIG_BT_IAS_SEC_AUTH BT_IAS_SEC_AUTH
#endif

//BT_IAS_SEC_ENC
#ifdef BT_IAS_SEC_ENC
    #define CONFIG_BT_IAS_SEC_ENC BT_IAS_SEC_ENC
#endif

//BT_IAS_SEC_NONE
#ifdef BT_IAS_SEC_NONE
    #define CONFIG_BT_IAS_SEC_NONE BT_IAS_SEC_NONE
#endif

//BT_ID_ALLOW_UNAUTH_OVERWRITE
#ifdef BT_ID_ALLOW_UNAUTH_OVERWRITE
    #define CONFIG_BT_ID_ALLOW_UNAUTH_OVERWRITE BT_ID_ALLOW_UNAUTH_OVERWRITE
#endif

//BT_ID_MAX
#ifdef BT_ID_MAX
    #define CONFIG_BT_ID_MAX BT_ID_MAX
#endif

//BT_ID_UNPAIR_MATCHING_BONDS
#ifdef BT_ID_UNPAIR_MATCHING_BONDS
    #define CONFIG_BT_ID_UNPAIR_MATCHING_BONDS BT_ID_UNPAIR_MATCHING_BONDS
#endif

//BT_ISO
#ifdef BT_ISO
    #define CONFIG_BT_ISO BT_ISO
#endif

//BT_ISO_BROADCAST
#ifdef BT_ISO_BROADCAST
    #define CONFIG_BT_ISO_BROADCAST BT_ISO_BROADCAST
#endif

//BT_ISO_BROADCASTER
#ifdef BT_ISO_BROADCASTER
    #define CONFIG_BT_ISO_BROADCASTER BT_ISO_BROADCASTER
#endif

//BT_ISO_CENTRAL
#ifdef BT_ISO_CENTRAL
    #define CONFIG_BT_ISO_CENTRAL BT_ISO_CENTRAL
#endif

//BT_ISO_MAX_BIG
#ifdef BT_ISO_MAX_BIG
    #define CONFIG_BT_ISO_MAX_BIG BT_ISO_MAX_BIG
#endif

//BT_ISO_MAX_CHAN
#ifdef BT_ISO_MAX_CHAN
    #define CONFIG_BT_ISO_MAX_CHAN BT_ISO_MAX_CHAN
#endif

//BT_ISO_MAX_CIG
#ifdef BT_ISO_MAX_CIG
    #define CONFIG_BT_ISO_MAX_CIG BT_ISO_MAX_CIG
#endif

//BT_ISO_PERIPHERAL
#ifdef BT_ISO_PERIPHERAL
    #define CONFIG_BT_ISO_PERIPHERAL BT_ISO_PERIPHERAL
#endif

//BT_ISO_RX
#ifdef BT_ISO_RX
    #define CONFIG_BT_ISO_RX BT_ISO_RX
#endif

//BT_ISO_RX_BUF_COUNT
#ifdef BT_ISO_RX_BUF_COUNT
    #define CONFIG_BT_ISO_RX_BUF_COUNT BT_ISO_RX_BUF_COUNT
#endif

//BT_ISO_RX_MTU
#ifdef BT_ISO_RX_MTU
    #define CONFIG_BT_ISO_RX_MTU BT_ISO_RX_MTU
#endif

//BT_ISO_SYNC_RECEIVER
#ifdef BT_ISO_SYNC_RECEIVER
    #define CONFIG_BT_ISO_SYNC_RECEIVER BT_ISO_SYNC_RECEIVER
#endif

//BT_ISO_TEST_PARAMS
#ifdef BT_ISO_TEST_PARAMS
    #define CONFIG_BT_ISO_TEST_PARAMS BT_ISO_TEST_PARAMS
#endif

//BT_ISO_TX
#ifdef BT_ISO_TX
    #define CONFIG_BT_ISO_TX BT_ISO_TX
#endif

//BT_ISO_TX_BUF_COUNT
#ifdef BT_ISO_TX_BUF_COUNT
    #define CONFIG_BT_ISO_TX_BUF_COUNT BT_ISO_TX_BUF_COUNT
#endif

//BT_ISO_TX_FRAG_COUNT
#ifdef BT_ISO_TX_FRAG_COUNT
    #define CONFIG_BT_ISO_TX_FRAG_COUNT BT_ISO_TX_FRAG_COUNT
#endif

//BT_ISO_TX_MTU
#ifdef BT_ISO_TX_MTU
    #define CONFIG_BT_ISO_TX_MTU BT_ISO_TX_MTU
#endif

//BT_ISO_UNICAST
#ifdef BT_ISO_UNICAST
    #define CONFIG_BT_ISO_UNICAST BT_ISO_UNICAST
#endif

//BT_KEYS_OVERWRITE_OLDEST
#ifdef BT_KEYS_OVERWRITE_OLDEST
    #define CONFIG_BT_KEYS_OVERWRITE_OLDEST BT_KEYS_OVERWRITE_OLDEST
#endif

//BT_L2CAP_DYNAMIC_CHANNEL
#ifdef BT_L2CAP_DYNAMIC_CHANNEL
    #define CONFIG_BT_L2CAP_DYNAMIC_CHANNEL BT_L2CAP_DYNAMIC_CHANNEL
#endif

//BT_L2CAP_ECRED
#ifdef BT_L2CAP_ECRED
    #define CONFIG_BT_L2CAP_ECRED BT_L2CAP_ECRED
#endif

//BT_L2CAP_SEG_RECV
#ifdef BT_L2CAP_SEG_RECV
    #define CONFIG_BT_L2CAP_SEG_RECV BT_L2CAP_SEG_RECV
#endif

//BT_L2CAP_TX_BUF_COUNT
#ifdef BT_L2CAP_TX_BUF_COUNT
    #define CONFIG_BT_L2CAP_TX_BUF_COUNT BT_L2CAP_TX_BUF_COUNT
#endif

//BT_L2CAP_TX_FRAG_COUNT
#ifdef BT_L2CAP_TX_FRAG_COUNT
    #define CONFIG_BT_L2CAP_TX_FRAG_COUNT BT_L2CAP_TX_FRAG_COUNT
#endif

//BT_L2CAP_TX_MTU
#ifdef BT_L2CAP_TX_MTU
    #define CONFIG_BT_L2CAP_TX_MTU BT_L2CAP_TX_MTU
#endif

//BT_LIM_ADV_TIMEOUT
#ifdef BT_LIM_ADV_TIMEOUT
    #define CONFIG_BT_LIM_ADV_TIMEOUT BT_LIM_ADV_TIMEOUT
#endif

//BT_LOG_SNIFFER_INFO
#ifdef BT_LOG_SNIFFER_INFO
    #define CONFIG_BT_LOG_SNIFFER_INFO BT_LOG_SNIFFER_INFO
#endif

//BT_LONG_WQ
#ifdef BT_LONG_WQ
    #define CONFIG_BT_LONG_WQ BT_LONG_WQ
#endif

//BT_LONG_WQ_INIT_PRIO
#ifdef BT_LONG_WQ_INIT_PRIO
    #define CONFIG_BT_LONG_WQ_INIT_PRIO BT_LONG_WQ_INIT_PRIO
#endif

//BT_LONG_WQ_PRIO
#ifdef BT_LONG_WQ_PRIO
    #define CONFIG_BT_LONG_WQ_PRIO BT_LONG_WQ_PRIO
#endif

//BT_LONG_WQ_STACK_SIZE
#ifdef BT_LONG_WQ_STACK_SIZE
    #define CONFIG_BT_LONG_WQ_STACK_SIZE BT_LONG_WQ_STACK_SIZE
#endif

//BT_MAX_CONN
#ifdef BT_MAX_CONN
    #define CONFIG_BT_MAX_CONN BT_MAX_CONN
#endif

//BT_MAX_PAIRED
#ifdef BT_MAX_PAIRED
    #define CONFIG_BT_MAX_PAIRED BT_MAX_PAIRED
#endif

//BT_MCC
#ifdef BT_MCC
    #define CONFIG_BT_MCC BT_MCC
#endif

//BT_MCC_ICON_URL_MAX
#ifdef BT_MCC_ICON_URL_MAX
    #define CONFIG_BT_MCC_ICON_URL_MAX BT_MCC_ICON_URL_MAX
#endif

//BT_MCC_MEDIA_PLAYER_NAME_MAX
#ifdef BT_MCC_MEDIA_PLAYER_NAME_MAX
    #define CONFIG_BT_MCC_MEDIA_PLAYER_NAME_MAX BT_MCC_MEDIA_PLAYER_NAME_MAX
#endif

//BT_MCC_MINIMAL
#ifdef BT_MCC_MINIMAL
    #define CONFIG_BT_MCC_MINIMAL BT_MCC_MINIMAL
#endif

//BT_MCC_READ_CONTENT_CONTROL_ID
#ifdef BT_MCC_READ_CONTENT_CONTROL_ID
    #define CONFIG_BT_MCC_READ_CONTENT_CONTROL_ID BT_MCC_READ_CONTENT_CONTROL_ID
#endif

//BT_MCC_READ_MEDIA_CONTROL_POINT_OPCODES_SUPPORTED
#ifdef BT_MCC_READ_MEDIA_CONTROL_POINT_OPCODES_SUPPORTED
    #define CONFIG_BT_MCC_READ_MEDIA_CONTROL_POINT_OPCODES_SUPPORTED BT_MCC_READ_MEDIA_CONTROL_POINT_OPCODES_SUPPORTED
#endif

//BT_MCC_READ_MEDIA_PLAYER_ICON_URL
#ifdef BT_MCC_READ_MEDIA_PLAYER_ICON_URL
    #define CONFIG_BT_MCC_READ_MEDIA_PLAYER_ICON_URL BT_MCC_READ_MEDIA_PLAYER_ICON_URL
#endif

//BT_MCC_READ_MEDIA_STATE
#ifdef BT_MCC_READ_MEDIA_STATE
    #define CONFIG_BT_MCC_READ_MEDIA_STATE BT_MCC_READ_MEDIA_STATE
#endif

//BT_MCC_READ_PLAYBACK_SPEED
#ifdef BT_MCC_READ_PLAYBACK_SPEED
    #define CONFIG_BT_MCC_READ_PLAYBACK_SPEED BT_MCC_READ_PLAYBACK_SPEED
#endif

//BT_MCC_READ_PLAYING_ORDER
#ifdef BT_MCC_READ_PLAYING_ORDER
    #define CONFIG_BT_MCC_READ_PLAYING_ORDER BT_MCC_READ_PLAYING_ORDER
#endif

//BT_MCC_READ_PLAYING_ORDER_SUPPORTED
#ifdef BT_MCC_READ_PLAYING_ORDER_SUPPORTED
    #define CONFIG_BT_MCC_READ_PLAYING_ORDER_SUPPORTED BT_MCC_READ_PLAYING_ORDER_SUPPORTED
#endif

//BT_MCC_READ_SEEKING_SPEED
#ifdef BT_MCC_READ_SEEKING_SPEED
    #define CONFIG_BT_MCC_READ_SEEKING_SPEED BT_MCC_READ_SEEKING_SPEED
#endif

//BT_MCC_READ_TRACK_DURATION
#ifdef BT_MCC_READ_TRACK_DURATION
    #define CONFIG_BT_MCC_READ_TRACK_DURATION BT_MCC_READ_TRACK_DURATION
#endif

//BT_MCC_READ_TRACK_POSITION
#ifdef BT_MCC_READ_TRACK_POSITION
    #define CONFIG_BT_MCC_READ_TRACK_POSITION BT_MCC_READ_TRACK_POSITION
#endif

//BT_MCC_READ_TRACK_TITLE
#ifdef BT_MCC_READ_TRACK_TITLE
    #define CONFIG_BT_MCC_READ_TRACK_TITLE BT_MCC_READ_TRACK_TITLE
#endif

//BT_MCC_READ_TRACK_TITLE_ENABLE_SUBSCRIPTION
#ifdef BT_MCC_READ_TRACK_TITLE_ENABLE_SUBSCRIPTION
    #define CONFIG_BT_MCC_READ_TRACK_TITLE_ENABLE_SUBSCRIPTION BT_MCC_READ_TRACK_TITLE_ENABLE_SUBSCRIPTION
#endif

//BT_MCC_SEGMENT_NAME_MAX
#ifdef BT_MCC_SEGMENT_NAME_MAX
    #define CONFIG_BT_MCC_SEGMENT_NAME_MAX BT_MCC_SEGMENT_NAME_MAX
#endif

//BT_MCC_SET_MEDIA_CONTROL_POINT
#ifdef BT_MCC_SET_MEDIA_CONTROL_POINT
    #define CONFIG_BT_MCC_SET_MEDIA_CONTROL_POINT BT_MCC_SET_MEDIA_CONTROL_POINT
#endif

//BT_MCC_SET_PLAYBACK_SPEED
#ifdef BT_MCC_SET_PLAYBACK_SPEED
    #define CONFIG_BT_MCC_SET_PLAYBACK_SPEED BT_MCC_SET_PLAYBACK_SPEED
#endif

//BT_MCC_SET_PLAYING_ORDER
#ifdef BT_MCC_SET_PLAYING_ORDER
    #define CONFIG_BT_MCC_SET_PLAYING_ORDER BT_MCC_SET_PLAYING_ORDER
#endif

//BT_MCC_SET_TRACK_POSITION
#ifdef BT_MCC_SET_TRACK_POSITION
    #define CONFIG_BT_MCC_SET_TRACK_POSITION BT_MCC_SET_TRACK_POSITION
#endif

//BT_MCC_SHELL
#ifdef BT_MCC_SHELL
    #define CONFIG_BT_MCC_SHELL BT_MCC_SHELL
#endif

//BT_MCC_TRACK_TITLE_MAX
#ifdef BT_MCC_TRACK_TITLE_MAX
    #define CONFIG_BT_MCC_TRACK_TITLE_MAX BT_MCC_TRACK_TITLE_MAX
#endif

//BT_MCS
#ifdef BT_MCS
    #define CONFIG_BT_MCS BT_MCS
#endif

//BT_MESH
#ifdef BT_MESH
    #define CONFIG_BT_MESH BT_MESH
#endif

//BT_MESH_ACCESS_DELAYABLE_MSG
#ifdef BT_MESH_ACCESS_DELAYABLE_MSG
    #define CONFIG_BT_MESH_ACCESS_DELAYABLE_MSG BT_MESH_ACCESS_DELAYABLE_MSG
#endif

//BT_MESH_ACCESS_DELAYABLE_MSG_CHUNK_COUNT
#ifdef BT_MESH_ACCESS_DELAYABLE_MSG_CHUNK_COUNT
    #define CONFIG_BT_MESH_ACCESS_DELAYABLE_MSG_CHUNK_COUNT BT_MESH_ACCESS_DELAYABLE_MSG_CHUNK_COUNT
#endif

//BT_MESH_ACCESS_DELAYABLE_MSG_CHUNK_SIZE
#ifdef BT_MESH_ACCESS_DELAYABLE_MSG_CHUNK_SIZE
    #define CONFIG_BT_MESH_ACCESS_DELAYABLE_MSG_CHUNK_SIZE BT_MESH_ACCESS_DELAYABLE_MSG_CHUNK_SIZE
#endif

//BT_MESH_ACCESS_DELAYABLE_MSG_COUNT
#ifdef BT_MESH_ACCESS_DELAYABLE_MSG_COUNT
    #define CONFIG_BT_MESH_ACCESS_DELAYABLE_MSG_COUNT BT_MESH_ACCESS_DELAYABLE_MSG_COUNT
#endif

//BT_MESH_ACCESS_DELAYABLE_MSG_CTX_ENABLED
#ifdef BT_MESH_ACCESS_DELAYABLE_MSG_CTX_ENABLED
    #define CONFIG_BT_MESH_ACCESS_DELAYABLE_MSG_CTX_ENABLED BT_MESH_ACCESS_DELAYABLE_MSG_CTX_ENABLED
#endif

//BT_MESH_ACCESS_LAYER_MSG
#ifdef BT_MESH_ACCESS_LAYER_MSG
    #define CONFIG_BT_MESH_ACCESS_LAYER_MSG BT_MESH_ACCESS_LAYER_MSG
#endif

//BT_MESH_ADV_BUF_COUNT
#ifdef BT_MESH_ADV_BUF_COUNT
    #define CONFIG_BT_MESH_ADV_BUF_COUNT BT_MESH_ADV_BUF_COUNT
#endif

//BT_MESH_ADV_EXT
#ifdef BT_MESH_ADV_EXT
    #define CONFIG_BT_MESH_ADV_EXT BT_MESH_ADV_EXT
#endif

//BT_MESH_ADV_EXT_FRIEND_SEPARATE
#ifdef BT_MESH_ADV_EXT_FRIEND_SEPARATE
    #define CONFIG_BT_MESH_ADV_EXT_FRIEND_SEPARATE BT_MESH_ADV_EXT_FRIEND_SEPARATE
#endif

//BT_MESH_ADV_EXT_GATT_SEPARATE
#ifdef BT_MESH_ADV_EXT_GATT_SEPARATE
    #define CONFIG_BT_MESH_ADV_EXT_GATT_SEPARATE BT_MESH_ADV_EXT_GATT_SEPARATE
#endif

//BT_MESH_ADV_LEGACY
#ifdef BT_MESH_ADV_LEGACY
    #define CONFIG_BT_MESH_ADV_LEGACY BT_MESH_ADV_LEGACY
#endif

//BT_MESH_ADV_PRIO
#ifdef BT_MESH_ADV_PRIO
    #define CONFIG_BT_MESH_ADV_PRIO BT_MESH_ADV_PRIO
#endif

//BT_MESH_ADV_STACK_SIZE
#ifdef BT_MESH_ADV_STACK_SIZE
    #define CONFIG_BT_MESH_ADV_STACK_SIZE BT_MESH_ADV_STACK_SIZE
#endif

//BT_MESH_ALIGN_CHUNK_SIZE_TO_MAX_SEGMENT
#ifdef BT_MESH_ALIGN_CHUNK_SIZE_TO_MAX_SEGMENT
    #define CONFIG_BT_MESH_ALIGN_CHUNK_SIZE_TO_MAX_SEGMENT BT_MESH_ALIGN_CHUNK_SIZE_TO_MAX_SEGMENT
#endif

//BT_MESH_APP_KEY_COUNT
#ifdef BT_MESH_APP_KEY_COUNT
    #define CONFIG_BT_MESH_APP_KEY_COUNT BT_MESH_APP_KEY_COUNT
#endif

//BT_MESH_BEACON_ENABLED
#ifdef BT_MESH_BEACON_ENABLED
    #define CONFIG_BT_MESH_BEACON_ENABLED BT_MESH_BEACON_ENABLED
#endif

//BT_MESH_BLOB_CHUNK_COUNT_MAX
#ifdef BT_MESH_BLOB_CHUNK_COUNT_MAX
    #define CONFIG_BT_MESH_BLOB_CHUNK_COUNT_MAX BT_MESH_BLOB_CHUNK_COUNT_MAX
#endif

//BT_MESH_BLOB_CLI
#ifdef BT_MESH_BLOB_CLI
    #define CONFIG_BT_MESH_BLOB_CLI BT_MESH_BLOB_CLI
#endif

//BT_MESH_BLOB_SRV
#ifdef BT_MESH_BLOB_SRV
    #define CONFIG_BT_MESH_BLOB_SRV BT_MESH_BLOB_SRV
#endif

//BT_MESH_BRG_CFG_CLI
#ifdef BT_MESH_BRG_CFG_CLI
    #define CONFIG_BT_MESH_BRG_CFG_CLI BT_MESH_BRG_CFG_CLI
#endif

//BT_MESH_BRG_CFG_SRV
#ifdef BT_MESH_BRG_CFG_SRV
    #define CONFIG_BT_MESH_BRG_CFG_SRV BT_MESH_BRG_CFG_SRV
#endif

//BT_MESH_BRG_TABLE_ITEMS_MAX
#ifdef BT_MESH_BRG_TABLE_ITEMS_MAX
    #define CONFIG_BT_MESH_BRG_TABLE_ITEMS_MAX BT_MESH_BRG_TABLE_ITEMS_MAX
#endif

//BT_MESH_CDB
#ifdef BT_MESH_CDB
    #define CONFIG_BT_MESH_CDB BT_MESH_CDB
#endif

//BT_MESH_CDB_APP_KEY_COUNT
#ifdef BT_MESH_CDB_APP_KEY_COUNT
    #define CONFIG_BT_MESH_CDB_APP_KEY_COUNT BT_MESH_CDB_APP_KEY_COUNT
#endif

//BT_MESH_CDB_NODE_COUNT
#ifdef BT_MESH_CDB_NODE_COUNT
    #define CONFIG_BT_MESH_CDB_NODE_COUNT BT_MESH_CDB_NODE_COUNT
#endif

//BT_MESH_CDB_SUBNET_COUNT
#ifdef BT_MESH_CDB_SUBNET_COUNT
    #define CONFIG_BT_MESH_CDB_SUBNET_COUNT BT_MESH_CDB_SUBNET_COUNT
#endif

//BT_MESH_CFG_CLI
#ifdef BT_MESH_CFG_CLI
    #define CONFIG_BT_MESH_CFG_CLI BT_MESH_CFG_CLI
#endif

//BT_MESH_CFG_CLI_TIMEOUT
#ifdef BT_MESH_CFG_CLI_TIMEOUT
    #define CONFIG_BT_MESH_CFG_CLI_TIMEOUT BT_MESH_CFG_CLI_TIMEOUT
#endif

//BT_MESH_COMP_PAGE_1
#ifdef BT_MESH_COMP_PAGE_1
    #define CONFIG_BT_MESH_COMP_PAGE_1 BT_MESH_COMP_PAGE_1
#endif

//BT_MESH_COMP_PAGE_2
#ifdef BT_MESH_COMP_PAGE_2
    #define CONFIG_BT_MESH_COMP_PAGE_2 BT_MESH_COMP_PAGE_2
#endif

//BT_MESH_COMP_PST_BUF_SIZE
#ifdef BT_MESH_COMP_PST_BUF_SIZE
    #define CONFIG_BT_MESH_COMP_PST_BUF_SIZE BT_MESH_COMP_PST_BUF_SIZE
#endif

//BT_MESH_CRPL
#ifdef BT_MESH_CRPL
    #define CONFIG_BT_MESH_CRPL BT_MESH_CRPL
#endif

//BT_MESH_DEBUG_USE_ID_ADDR
#ifdef BT_MESH_DEBUG_USE_ID_ADDR
    #define CONFIG_BT_MESH_DEBUG_USE_ID_ADDR BT_MESH_DEBUG_USE_ID_ADDR
#endif

//BT_MESH_DEFAULT_TTL
#ifdef BT_MESH_DEFAULT_TTL
    #define CONFIG_BT_MESH_DEFAULT_TTL BT_MESH_DEFAULT_TTL
#endif

//BT_MESH_DELAYABLE_PUBLICATION
#ifdef BT_MESH_DELAYABLE_PUBLICATION
    #define CONFIG_BT_MESH_DELAYABLE_PUBLICATION BT_MESH_DELAYABLE_PUBLICATION
#endif

//BT_MESH_DFU_FWID_MAXLEN
#ifdef BT_MESH_DFU_FWID_MAXLEN
    #define CONFIG_BT_MESH_DFU_FWID_MAXLEN BT_MESH_DFU_FWID_MAXLEN
#endif

//BT_MESH_DFU_METADATA_MAXLEN
#ifdef BT_MESH_DFU_METADATA_MAXLEN
    #define CONFIG_BT_MESH_DFU_METADATA_MAXLEN BT_MESH_DFU_METADATA_MAXLEN
#endif

//BT_MESH_DFU_SLOTS
#ifdef BT_MESH_DFU_SLOTS
    #define CONFIG_BT_MESH_DFU_SLOTS BT_MESH_DFU_SLOTS
#endif

//BT_MESH_DFU_URI_MAXLEN
#ifdef BT_MESH_DFU_URI_MAXLEN
    #define CONFIG_BT_MESH_DFU_URI_MAXLEN BT_MESH_DFU_URI_MAXLEN
#endif

//BT_MESH_ECDH_P256_CMAC_AES128_AES_CCM
#ifdef BT_MESH_ECDH_P256_CMAC_AES128_AES_CCM
    #define CONFIG_BT_MESH_ECDH_P256_CMAC_AES128_AES_CCM BT_MESH_ECDH_P256_CMAC_AES128_AES_CCM
#endif

//BT_MESH_ECDH_P256_HMAC_SHA256_AES_CCM
#ifdef BT_MESH_ECDH_P256_HMAC_SHA256_AES_CCM
    #define CONFIG_BT_MESH_ECDH_P256_HMAC_SHA256_AES_CCM BT_MESH_ECDH_P256_HMAC_SHA256_AES_CCM
#endif

//BT_MESH_FRIEND2
#ifdef BT_MESH_FRIEND2
    #define CONFIG_BT_MESH_FRIEND BT_MESH_FRIEND2
#endif

//BT_MESH_FRIEND_ADV_LATENCY
#ifdef BT_MESH_FRIEND_ADV_LATENCY
    #define CONFIG_BT_MESH_FRIEND_ADV_LATENCY BT_MESH_FRIEND_ADV_LATENCY
#endif

//BT_MESH_FRIEND_ENABLED
#ifdef BT_MESH_FRIEND_ENABLED
    #define CONFIG_BT_MESH_FRIEND_ENABLED BT_MESH_FRIEND_ENABLED
#endif

//BT_MESH_FRIEND_LPN_COUNT
#ifdef BT_MESH_FRIEND_LPN_COUNT
    #define CONFIG_BT_MESH_FRIEND_LPN_COUNT BT_MESH_FRIEND_LPN_COUNT
#endif

//BT_MESH_FRIEND_QUEUE_SIZE
#ifdef BT_MESH_FRIEND_QUEUE_SIZE
    #define CONFIG_BT_MESH_FRIEND_QUEUE_SIZE BT_MESH_FRIEND_QUEUE_SIZE
#endif

//BT_MESH_FRIEND_RECV_WIN
#ifdef BT_MESH_FRIEND_RECV_WIN
    #define CONFIG_BT_MESH_FRIEND_RECV_WIN BT_MESH_FRIEND_RECV_WIN
#endif

//BT_MESH_FRIEND_SEG_RX
#ifdef BT_MESH_FRIEND_SEG_RX
    #define CONFIG_BT_MESH_FRIEND_SEG_RX BT_MESH_FRIEND_SEG_RX
#endif

//BT_MESH_FRIEND_SUB_LIST_SIZE
#ifdef BT_MESH_FRIEND_SUB_LIST_SIZE
    #define CONFIG_BT_MESH_FRIEND_SUB_LIST_SIZE BT_MESH_FRIEND_SUB_LIST_SIZE
#endif

//BT_MESH_GATT
#ifdef BT_MESH_GATT
    #define CONFIG_BT_MESH_GATT BT_MESH_GATT
#endif

//BT_MESH_GATT_PROXY2
#ifdef BT_MESH_GATT_PROXY2
    #define CONFIG_BT_MESH_GATT_PROXY BT_MESH_GATT_PROXY2
#endif

//BT_MESH_GATT_PROXY_ENABLED
#ifdef BT_MESH_GATT_PROXY_ENABLED
    #define CONFIG_BT_MESH_GATT_PROXY_ENABLED BT_MESH_GATT_PROXY_ENABLED
#endif

//BT_MESH_GATT_SERVER
#ifdef BT_MESH_GATT_SERVER
    #define CONFIG_BT_MESH_GATT_SERVER BT_MESH_GATT_SERVER
#endif

//BT_MESH_HEALTH_CLI
#ifdef BT_MESH_HEALTH_CLI
    #define CONFIG_BT_MESH_HEALTH_CLI BT_MESH_HEALTH_CLI
#endif

//BT_MESH_HEALTH_CLI_TIMEOUT
#ifdef BT_MESH_HEALTH_CLI_TIMEOUT
    #define CONFIG_BT_MESH_HEALTH_CLI_TIMEOUT BT_MESH_HEALTH_CLI_TIMEOUT
#endif

//BT_MESH_IVU_DIVIDER
#ifdef BT_MESH_IVU_DIVIDER
    #define CONFIG_BT_MESH_IVU_DIVIDER BT_MESH_IVU_DIVIDER
#endif

//BT_MESH_IV_UPDATE_SEQ_LIMIT
#ifdef BT_MESH_IV_UPDATE_SEQ_LIMIT
    #define CONFIG_BT_MESH_IV_UPDATE_SEQ_LIMIT BT_MESH_IV_UPDATE_SEQ_LIMIT
#endif

//BT_MESH_IV_UPDATE_TEST
#ifdef BT_MESH_IV_UPDATE_TEST
    #define CONFIG_BT_MESH_IV_UPDATE_TEST BT_MESH_IV_UPDATE_TEST
#endif

//BT_MESH_LABEL_COUNT
#ifdef BT_MESH_LABEL_COUNT
    #define CONFIG_BT_MESH_LABEL_COUNT BT_MESH_LABEL_COUNT
#endif

//BT_MESH_LARGE_COMP_DATA_CLI
#ifdef BT_MESH_LARGE_COMP_DATA_CLI
    #define CONFIG_BT_MESH_LARGE_COMP_DATA_CLI BT_MESH_LARGE_COMP_DATA_CLI
#endif

//BT_MESH_LARGE_COMP_DATA_SRV
#ifdef BT_MESH_LARGE_COMP_DATA_SRV
    #define CONFIG_BT_MESH_LARGE_COMP_DATA_SRV BT_MESH_LARGE_COMP_DATA_SRV
#endif

//BT_MESH_LOOPBACK_BUFS
#ifdef BT_MESH_LOOPBACK_BUFS
    #define CONFIG_BT_MESH_LOOPBACK_BUFS BT_MESH_LOOPBACK_BUFS
#endif

//BT_MESH_LOW_POWER
#ifdef BT_MESH_LOW_POWER
    #define CONFIG_BT_MESH_LOW_POWER BT_MESH_LOW_POWER
#endif

//BT_MESH_LPN_AUTO
#ifdef BT_MESH_LPN_AUTO
    #define CONFIG_BT_MESH_LPN_AUTO BT_MESH_LPN_AUTO
#endif

//BT_MESH_LPN_AUTO_TIMEOUT
#ifdef BT_MESH_LPN_AUTO_TIMEOUT
    #define CONFIG_BT_MESH_LPN_AUTO_TIMEOUT BT_MESH_LPN_AUTO_TIMEOUT
#endif

//BT_MESH_LPN_ESTABLISHMENT
#ifdef BT_MESH_LPN_ESTABLISHMENT
    #define CONFIG_BT_MESH_LPN_ESTABLISHMENT BT_MESH_LPN_ESTABLISHMENT
#endif

//BT_MESH_LPN_GROUPS
#ifdef BT_MESH_LPN_GROUPS
    #define CONFIG_BT_MESH_LPN_GROUPS BT_MESH_LPN_GROUPS
#endif

//BT_MESH_LPN_INIT_POLL_TIMEOUT
#ifdef BT_MESH_LPN_INIT_POLL_TIMEOUT
    #define CONFIG_BT_MESH_LPN_INIT_POLL_TIMEOUT BT_MESH_LPN_INIT_POLL_TIMEOUT
#endif

//BT_MESH_LPN_MIN_QUEUE_SIZE
#ifdef BT_MESH_LPN_MIN_QUEUE_SIZE
    #define CONFIG_BT_MESH_LPN_MIN_QUEUE_SIZE BT_MESH_LPN_MIN_QUEUE_SIZE
#endif

//BT_MESH_LPN_POLL_TIMEOUT
#ifdef BT_MESH_LPN_POLL_TIMEOUT
    #define CONFIG_BT_MESH_LPN_POLL_TIMEOUT BT_MESH_LPN_POLL_TIMEOUT
#endif

//BT_MESH_LPN_RECV_DELAY2
#ifdef BT_MESH_LPN_RECV_DELAY2
    #define CONFIG_BT_MESH_LPN_RECV_DELAY BT_MESH_LPN_RECV_DELAY2
#endif

//BT_MESH_LPN_RECV_WIN_FACTOR
#ifdef BT_MESH_LPN_RECV_WIN_FACTOR
    #define CONFIG_BT_MESH_LPN_RECV_WIN_FACTOR BT_MESH_LPN_RECV_WIN_FACTOR
#endif

//BT_MESH_LPN_RETRY_TIMEOUT
#ifdef BT_MESH_LPN_RETRY_TIMEOUT
    #define CONFIG_BT_MESH_LPN_RETRY_TIMEOUT BT_MESH_LPN_RETRY_TIMEOUT
#endif

//BT_MESH_LPN_RSSI_FACTOR
#ifdef BT_MESH_LPN_RSSI_FACTOR
    #define CONFIG_BT_MESH_LPN_RSSI_FACTOR BT_MESH_LPN_RSSI_FACTOR
#endif

//BT_MESH_LPN_SCAN_LATENCY
#ifdef BT_MESH_LPN_SCAN_LATENCY
    #define CONFIG_BT_MESH_LPN_SCAN_LATENCY BT_MESH_LPN_SCAN_LATENCY
#endif

//BT_MESH_LPN_SUB_ALL_NODES_ADDR
#ifdef BT_MESH_LPN_SUB_ALL_NODES_ADDR
    #define CONFIG_BT_MESH_LPN_SUB_ALL_NODES_ADDR BT_MESH_LPN_SUB_ALL_NODES_ADDR
#endif

//BT_MESH_MAX_CONN
#ifdef BT_MESH_MAX_CONN
    #define CONFIG_BT_MESH_MAX_CONN BT_MESH_MAX_CONN
#endif

//BT_MESH_MODEL_EXTENSIONS
#ifdef BT_MESH_MODEL_EXTENSIONS
    #define CONFIG_BT_MESH_MODEL_EXTENSIONS BT_MESH_MODEL_EXTENSIONS
#endif

//BT_MESH_MODEL_EXTENSION_LIST_SIZE
#ifdef BT_MESH_MODEL_EXTENSION_LIST_SIZE
    #define CONFIG_BT_MESH_MODEL_EXTENSION_LIST_SIZE BT_MESH_MODEL_EXTENSION_LIST_SIZE
#endif

//BT_MESH_MODEL_GROUP_COUNT
#ifdef BT_MESH_MODEL_GROUP_COUNT
    #define CONFIG_BT_MESH_MODEL_GROUP_COUNT BT_MESH_MODEL_GROUP_COUNT
#endif

//BT_MESH_MODEL_KEY_COUNT
#ifdef BT_MESH_MODEL_KEY_COUNT
    #define CONFIG_BT_MESH_MODEL_KEY_COUNT BT_MESH_MODEL_KEY_COUNT
#endif

//BT_MESH_MODEL_VND_MSG_CID_FORCE
#ifdef BT_MESH_MODEL_VND_MSG_CID_FORCE
    #define CONFIG_BT_MESH_MODEL_VND_MSG_CID_FORCE BT_MESH_MODEL_VND_MSG_CID_FORCE
#endif

//BT_MESH_MSG_CACHE_SIZE
#ifdef BT_MESH_MSG_CACHE_SIZE
    #define CONFIG_BT_MESH_MSG_CACHE_SIZE BT_MESH_MSG_CACHE_SIZE
#endif

//BT_MESH_NETWORK_TRANSMIT_COUNT
#ifdef BT_MESH_NETWORK_TRANSMIT_COUNT
    #define CONFIG_BT_MESH_NETWORK_TRANSMIT_COUNT BT_MESH_NETWORK_TRANSMIT_COUNT
#endif

//BT_MESH_NETWORK_TRANSMIT_INTERVAL
#ifdef BT_MESH_NETWORK_TRANSMIT_INTERVAL
    #define CONFIG_BT_MESH_NETWORK_TRANSMIT_INTERVAL BT_MESH_NETWORK_TRANSMIT_INTERVAL
#endif

//BT_MESH_NODE_ID_TIMEOUT
#ifdef BT_MESH_NODE_ID_TIMEOUT
    #define CONFIG_BT_MESH_NODE_ID_TIMEOUT BT_MESH_NODE_ID_TIMEOUT
#endif

//BT_MESH_OD_PRIV_PROXY_CLI
#ifdef BT_MESH_OD_PRIV_PROXY_CLI
    #define CONFIG_BT_MESH_OD_PRIV_PROXY_CLI BT_MESH_OD_PRIV_PROXY_CLI
#endif

//BT_MESH_OOB_AUTH_REQUIRED
#ifdef BT_MESH_OOB_AUTH_REQUIRED
    #define CONFIG_BT_MESH_OOB_AUTH_REQUIRED BT_MESH_OOB_AUTH_REQUIRED
#endif

//BT_MESH_OP_AGG_CLI
#ifdef BT_MESH_OP_AGG_CLI
    #define CONFIG_BT_MESH_OP_AGG_CLI BT_MESH_OP_AGG_CLI
#endif

//BT_MESH_OP_AGG_SRV
#ifdef BT_MESH_OP_AGG_SRV
    #define CONFIG_BT_MESH_OP_AGG_SRV BT_MESH_OP_AGG_SRV
#endif

//BT_MESH_PB_ADV
#ifdef BT_MESH_PB_ADV
    #define CONFIG_BT_MESH_PB_ADV BT_MESH_PB_ADV
#endif

//BT_MESH_PB_ADV_LINK_CLOSE_RETRANSMIT_COUNT
#ifdef BT_MESH_PB_ADV_LINK_CLOSE_RETRANSMIT_COUNT
    #define CONFIG_BT_MESH_PB_ADV_LINK_CLOSE_RETRANSMIT_COUNT BT_MESH_PB_ADV_LINK_CLOSE_RETRANSMIT_COUNT
#endif

//BT_MESH_PB_ADV_RETRANS_TIMEOUT
#ifdef BT_MESH_PB_ADV_RETRANS_TIMEOUT
    #define CONFIG_BT_MESH_PB_ADV_RETRANS_TIMEOUT BT_MESH_PB_ADV_RETRANS_TIMEOUT
#endif

//BT_MESH_PB_ADV_TRANS_ACK_RETRANSMIT_COUNT
#ifdef BT_MESH_PB_ADV_TRANS_ACK_RETRANSMIT_COUNT
    #define CONFIG_BT_MESH_PB_ADV_TRANS_ACK_RETRANSMIT_COUNT BT_MESH_PB_ADV_TRANS_ACK_RETRANSMIT_COUNT
#endif

//BT_MESH_PB_ADV_TRANS_PDU_RETRANSMIT_COUNT
#ifdef BT_MESH_PB_ADV_TRANS_PDU_RETRANSMIT_COUNT
    #define CONFIG_BT_MESH_PB_ADV_TRANS_PDU_RETRANSMIT_COUNT BT_MESH_PB_ADV_TRANS_PDU_RETRANSMIT_COUNT
#endif

//BT_MESH_PB_GATT
#ifdef BT_MESH_PB_GATT
    #define CONFIG_BT_MESH_PB_GATT BT_MESH_PB_GATT
#endif

//BT_MESH_PB_GATT_COMMON
#ifdef BT_MESH_PB_GATT_COMMON
    #define CONFIG_BT_MESH_PB_GATT_COMMON BT_MESH_PB_GATT_COMMON
#endif

//BT_MESH_PB_GATT_USE_DEVICE_NAME
#ifdef BT_MESH_PB_GATT_USE_DEVICE_NAME
    #define CONFIG_BT_MESH_PB_GATT_USE_DEVICE_NAME BT_MESH_PB_GATT_USE_DEVICE_NAME
#endif

//BT_MESH_PRIV_BEACONS
#ifdef BT_MESH_PRIV_BEACONS
    #define CONFIG_BT_MESH_PRIV_BEACONS BT_MESH_PRIV_BEACONS
#endif

//BT_MESH_PRIV_BEACON_CLI
#ifdef BT_MESH_PRIV_BEACON_CLI
    #define CONFIG_BT_MESH_PRIV_BEACON_CLI BT_MESH_PRIV_BEACON_CLI
#endif

//BT_MESH_PRIV_BEACON_SRV
#ifdef BT_MESH_PRIV_BEACON_SRV
    #define CONFIG_BT_MESH_PRIV_BEACON_SRV BT_MESH_PRIV_BEACON_SRV
#endif

//BT_MESH_PROV
#ifdef BT_MESH_PROV
    #define CONFIG_BT_MESH_PROV BT_MESH_PROV
#endif

//BT_MESH_PROVISIONEE
#ifdef BT_MESH_PROVISIONEE
    #define CONFIG_BT_MESH_PROVISIONEE BT_MESH_PROVISIONEE
#endif

//BT_MESH_PROVISIONER
#ifdef BT_MESH_PROVISIONER
    #define CONFIG_BT_MESH_PROVISIONER BT_MESH_PROVISIONER
#endif

//BT_MESH_PROV_DEVICE
#ifdef BT_MESH_PROV_DEVICE
    #define CONFIG_BT_MESH_PROV_DEVICE BT_MESH_PROV_DEVICE
#endif

//BT_MESH_PROV_OOB_PUBLIC_KEY
#ifdef BT_MESH_PROV_OOB_PUBLIC_KEY
    #define CONFIG_BT_MESH_PROV_OOB_PUBLIC_KEY BT_MESH_PROV_OOB_PUBLIC_KEY
#endif

//BT_MESH_PROXY
#ifdef BT_MESH_PROXY
    #define CONFIG_BT_MESH_PROXY BT_MESH_PROXY
#endif

//BT_MESH_PROXY_FILTER_SIZE
#ifdef BT_MESH_PROXY_FILTER_SIZE
    #define CONFIG_BT_MESH_PROXY_FILTER_SIZE BT_MESH_PROXY_FILTER_SIZE
#endif

//BT_MESH_PROXY_MSG_LEN
#ifdef BT_MESH_PROXY_MSG_LEN
    #define CONFIG_BT_MESH_PROXY_MSG_LEN BT_MESH_PROXY_MSG_LEN
#endif

//BT_MESH_PROXY_SOLICITATION
#ifdef BT_MESH_PROXY_SOLICITATION
    #define CONFIG_BT_MESH_PROXY_SOLICITATION BT_MESH_PROXY_SOLICITATION
#endif

//BT_MESH_PROXY_USE_DEVICE_NAME
#ifdef BT_MESH_PROXY_USE_DEVICE_NAME
    #define CONFIG_BT_MESH_PROXY_USE_DEVICE_NAME BT_MESH_PROXY_USE_DEVICE_NAME
#endif

//BT_MESH_RELAY2
#ifdef BT_MESH_RELAY2
    #define CONFIG_BT_MESH_RELAY BT_MESH_RELAY2
#endif

//BT_MESH_RELAY_ADV_SETS
#ifdef BT_MESH_RELAY_ADV_SETS
    #define CONFIG_BT_MESH_RELAY_ADV_SETS BT_MESH_RELAY_ADV_SETS
#endif

//BT_MESH_RELAY_BUF_COUNT
#ifdef BT_MESH_RELAY_BUF_COUNT
    #define CONFIG_BT_MESH_RELAY_BUF_COUNT BT_MESH_RELAY_BUF_COUNT
#endif

//BT_MESH_RELAY_ENABLED
#ifdef BT_MESH_RELAY_ENABLED
    #define CONFIG_BT_MESH_RELAY_ENABLED BT_MESH_RELAY_ENABLED
#endif

//BT_MESH_RELAY_RETRANSMIT_COUNT
#ifdef BT_MESH_RELAY_RETRANSMIT_COUNT
    #define CONFIG_BT_MESH_RELAY_RETRANSMIT_COUNT BT_MESH_RELAY_RETRANSMIT_COUNT
#endif

//BT_MESH_RELAY_RETRANSMIT_INTERVAL
#ifdef BT_MESH_RELAY_RETRANSMIT_INTERVAL
    #define CONFIG_BT_MESH_RELAY_RETRANSMIT_INTERVAL BT_MESH_RELAY_RETRANSMIT_INTERVAL
#endif

//BT_MESH_RPL_STORAGE_MODE_SETTINGS
#ifdef BT_MESH_RPL_STORAGE_MODE_SETTINGS
    #define CONFIG_BT_MESH_RPL_STORAGE_MODE_SETTINGS BT_MESH_RPL_STORAGE_MODE_SETTINGS
#endif

//BT_MESH_RPR_AD_TYPES_MAX
#ifdef BT_MESH_RPR_AD_TYPES_MAX
    #define CONFIG_BT_MESH_RPR_AD_TYPES_MAX BT_MESH_RPR_AD_TYPES_MAX
#endif

//BT_MESH_RPR_CLI
#ifdef BT_MESH_RPR_CLI
    #define CONFIG_BT_MESH_RPR_CLI BT_MESH_RPR_CLI
#endif

//BT_MESH_RPR_SRV
#ifdef BT_MESH_RPR_SRV
    #define CONFIG_BT_MESH_RPR_SRV BT_MESH_RPR_SRV
#endif

//BT_MESH_RPR_SRV_AD_DATA_MAX
#ifdef BT_MESH_RPR_SRV_AD_DATA_MAX
    #define CONFIG_BT_MESH_RPR_SRV_AD_DATA_MAX BT_MESH_RPR_SRV_AD_DATA_MAX
#endif

//BT_MESH_RPR_SRV_SCANNED_ITEMS_MAX
#ifdef BT_MESH_RPR_SRV_SCANNED_ITEMS_MAX
    #define CONFIG_BT_MESH_RPR_SRV_SCANNED_ITEMS_MAX BT_MESH_RPR_SRV_SCANNED_ITEMS_MAX
#endif

//BT_MESH_RX_SEG_MAX
#ifdef BT_MESH_RX_SEG_MAX
    #define CONFIG_BT_MESH_RX_SEG_MAX BT_MESH_RX_SEG_MAX
#endif

//BT_MESH_RX_SEG_MSG_COUNT
#ifdef BT_MESH_RX_SEG_MSG_COUNT
    #define CONFIG_BT_MESH_RX_SEG_MSG_COUNT BT_MESH_RX_SEG_MSG_COUNT
#endif

//BT_MESH_SAR_CFG_CLI
#ifdef BT_MESH_SAR_CFG_CLI
    #define CONFIG_BT_MESH_SAR_CFG_CLI BT_MESH_SAR_CFG_CLI
#endif

//BT_MESH_SAR_CFG_SRV
#ifdef BT_MESH_SAR_CFG_SRV
    #define CONFIG_BT_MESH_SAR_CFG_SRV BT_MESH_SAR_CFG_SRV
#endif

//BT_MESH_SAR_RX_ACK_DELAY_INC
#ifdef BT_MESH_SAR_RX_ACK_DELAY_INC
    #define CONFIG_BT_MESH_SAR_RX_ACK_DELAY_INC BT_MESH_SAR_RX_ACK_DELAY_INC
#endif

//BT_MESH_SAR_RX_ACK_RETRANS_COUNT2
#ifdef BT_MESH_SAR_RX_ACK_RETRANS_COUNT2
    #define CONFIG_BT_MESH_SAR_RX_ACK_RETRANS_COUNT BT_MESH_SAR_RX_ACK_RETRANS_COUNT2
#endif

//BT_MESH_SAR_RX_DISCARD_TIMEOUT
#ifdef BT_MESH_SAR_RX_DISCARD_TIMEOUT
    #define CONFIG_BT_MESH_SAR_RX_DISCARD_TIMEOUT BT_MESH_SAR_RX_DISCARD_TIMEOUT
#endif

//BT_MESH_SAR_RX_SEG_INT_STEP
#ifdef BT_MESH_SAR_RX_SEG_INT_STEP
    #define CONFIG_BT_MESH_SAR_RX_SEG_INT_STEP BT_MESH_SAR_RX_SEG_INT_STEP
#endif

//BT_MESH_SAR_RX_SEG_THRESHOLD2
#ifdef BT_MESH_SAR_RX_SEG_THRESHOLD2
    #define CONFIG_BT_MESH_SAR_RX_SEG_THRESHOLD BT_MESH_SAR_RX_SEG_THRESHOLD2
#endif

//BT_MESH_SAR_TX_MULTICAST_RETRANS_COUNT
#ifdef BT_MESH_SAR_TX_MULTICAST_RETRANS_COUNT
    #define CONFIG_BT_MESH_SAR_TX_MULTICAST_RETRANS_COUNT BT_MESH_SAR_TX_MULTICAST_RETRANS_COUNT
#endif

//BT_MESH_SAR_TX_MULTICAST_RETRANS_INT
#ifdef BT_MESH_SAR_TX_MULTICAST_RETRANS_INT
    #define CONFIG_BT_MESH_SAR_TX_MULTICAST_RETRANS_INT BT_MESH_SAR_TX_MULTICAST_RETRANS_INT
#endif

//BT_MESH_SAR_TX_SEG_INT_STEP
#ifdef BT_MESH_SAR_TX_SEG_INT_STEP
    #define CONFIG_BT_MESH_SAR_TX_SEG_INT_STEP BT_MESH_SAR_TX_SEG_INT_STEP
#endif

//BT_MESH_SAR_TX_UNICAST_RETRANS_COUNT
#ifdef BT_MESH_SAR_TX_UNICAST_RETRANS_COUNT
    #define CONFIG_BT_MESH_SAR_TX_UNICAST_RETRANS_COUNT BT_MESH_SAR_TX_UNICAST_RETRANS_COUNT
#endif

//BT_MESH_SAR_TX_UNICAST_RETRANS_INT_INC
#ifdef BT_MESH_SAR_TX_UNICAST_RETRANS_INT_INC
    #define CONFIG_BT_MESH_SAR_TX_UNICAST_RETRANS_INT_INC BT_MESH_SAR_TX_UNICAST_RETRANS_INT_INC
#endif

//BT_MESH_SAR_TX_UNICAST_RETRANS_INT_STEP
#ifdef BT_MESH_SAR_TX_UNICAST_RETRANS_INT_STEP
    #define CONFIG_BT_MESH_SAR_TX_UNICAST_RETRANS_INT_STEP BT_MESH_SAR_TX_UNICAST_RETRANS_INT_STEP
#endif

//BT_MESH_SAR_TX_UNICAST_RETRANS_WITHOUT_PROG_COUNT
#ifdef BT_MESH_SAR_TX_UNICAST_RETRANS_WITHOUT_PROG_COUNT
    #define CONFIG_BT_MESH_SAR_TX_UNICAST_RETRANS_WITHOUT_PROG_COUNT BT_MESH_SAR_TX_UNICAST_RETRANS_WITHOUT_PROG_COUNT
#endif

//BT_MESH_SEG_BUFS
#ifdef BT_MESH_SEG_BUFS
    #define CONFIG_BT_MESH_SEG_BUFS BT_MESH_SEG_BUFS
#endif

//BT_MESH_SELF_TEST
#ifdef BT_MESH_SELF_TEST
    #define CONFIG_BT_MESH_SELF_TEST BT_MESH_SELF_TEST
#endif

//BT_MESH_SEQ_STORE_RATE
#ifdef BT_MESH_SEQ_STORE_RATE
    #define CONFIG_BT_MESH_SEQ_STORE_RATE BT_MESH_SEQ_STORE_RATE
#endif

//BT_MESH_SETTINGS_WORKQ
#ifdef BT_MESH_SETTINGS_WORKQ
    #define CONFIG_BT_MESH_SETTINGS_WORKQ BT_MESH_SETTINGS_WORKQ
#endif

//BT_MESH_SETTINGS_WORKQ_PRIO
#ifdef BT_MESH_SETTINGS_WORKQ_PRIO
    #define CONFIG_BT_MESH_SETTINGS_WORKQ_PRIO BT_MESH_SETTINGS_WORKQ_PRIO
#endif

//BT_MESH_SETTINGS_WORKQ_STACK_SIZE
#ifdef BT_MESH_SETTINGS_WORKQ_STACK_SIZE
    #define CONFIG_BT_MESH_SETTINGS_WORKQ_STACK_SIZE BT_MESH_SETTINGS_WORKQ_STACK_SIZE
#endif

//BT_MESH_SHELL
#ifdef BT_MESH_SHELL
    #define CONFIG_BT_MESH_SHELL BT_MESH_SHELL
#endif

//BT_MESH_SHELL_CDB
#ifdef BT_MESH_SHELL_CDB
    #define CONFIG_BT_MESH_SHELL_CDB BT_MESH_SHELL_CDB
#endif

//BT_MESH_SHELL_CFG_CLI
#ifdef BT_MESH_SHELL_CFG_CLI
    #define CONFIG_BT_MESH_SHELL_CFG_CLI BT_MESH_SHELL_CFG_CLI
#endif

//BT_MESH_SHELL_GATT_PROXY
#ifdef BT_MESH_SHELL_GATT_PROXY
    #define CONFIG_BT_MESH_SHELL_GATT_PROXY BT_MESH_SHELL_GATT_PROXY
#endif

//BT_MESH_SHELL_HEALTH_CLI
#ifdef BT_MESH_SHELL_HEALTH_CLI
    #define CONFIG_BT_MESH_SHELL_HEALTH_CLI BT_MESH_SHELL_HEALTH_CLI
#endif

//BT_MESH_SHELL_HEALTH_SRV_INSTANCE
#ifdef BT_MESH_SHELL_HEALTH_SRV_INSTANCE
    #define CONFIG_BT_MESH_SHELL_HEALTH_SRV_INSTANCE BT_MESH_SHELL_HEALTH_SRV_INSTANCE
#endif

//BT_MESH_SHELL_LOW_POWER
#ifdef BT_MESH_SHELL_LOW_POWER
    #define CONFIG_BT_MESH_SHELL_LOW_POWER BT_MESH_SHELL_LOW_POWER
#endif

//BT_MESH_SHELL_PROV
#ifdef BT_MESH_SHELL_PROV
    #define CONFIG_BT_MESH_SHELL_PROV BT_MESH_SHELL_PROV
#endif

//BT_MESH_SHELL_PROV_CTX_INSTANCE
#ifdef BT_MESH_SHELL_PROV_CTX_INSTANCE
    #define CONFIG_BT_MESH_SHELL_PROV_CTX_INSTANCE BT_MESH_SHELL_PROV_CTX_INSTANCE
#endif

//BT_MESH_SHELL_TEST
#ifdef BT_MESH_SHELL_TEST
    #define CONFIG_BT_MESH_SHELL_TEST BT_MESH_SHELL_TEST
#endif

//BT_MESH_SOL_PDU_RPL_CLI
#ifdef BT_MESH_SOL_PDU_RPL_CLI
    #define CONFIG_BT_MESH_SOL_PDU_RPL_CLI BT_MESH_SOL_PDU_RPL_CLI
#endif

//BT_MESH_STATISTIC
#ifdef BT_MESH_STATISTIC
    #define CONFIG_BT_MESH_STATISTIC BT_MESH_STATISTIC
#endif

//BT_MESH_STORE_TIMEOUT
#ifdef BT_MESH_STORE_TIMEOUT
    #define CONFIG_BT_MESH_STORE_TIMEOUT BT_MESH_STORE_TIMEOUT
#endif

//BT_MESH_SUBNET_COUNT
#ifdef BT_MESH_SUBNET_COUNT
    #define CONFIG_BT_MESH_SUBNET_COUNT BT_MESH_SUBNET_COUNT
#endif

//BT_MESH_TX_SEG_MAX
#ifdef BT_MESH_TX_SEG_MAX
    #define CONFIG_BT_MESH_TX_SEG_MAX BT_MESH_TX_SEG_MAX
#endif

//BT_MESH_TX_SEG_MSG_COUNT
#ifdef BT_MESH_TX_SEG_MSG_COUNT
    #define CONFIG_BT_MESH_TX_SEG_MSG_COUNT BT_MESH_TX_SEG_MSG_COUNT
#endif

//BT_MESH_UNPROV_BEACON_INT
#ifdef BT_MESH_UNPROV_BEACON_INT
    #define CONFIG_BT_MESH_UNPROV_BEACON_INT BT_MESH_UNPROV_BEACON_INT
#endif

//BT_MESH_USES_MBEDTLS_PSA
#ifdef BT_MESH_USES_MBEDTLS_PSA
    #define CONFIG_BT_MESH_USES_MBEDTLS_PSA BT_MESH_USES_MBEDTLS_PSA
#endif

//BT_MESH_USES_TINYCRYPT
#ifdef BT_MESH_USES_TINYCRYPT
    #define CONFIG_BT_MESH_USES_TINYCRYPT BT_MESH_USES_TINYCRYPT
#endif

//BT_MICP_MIC_CTLR
#ifdef BT_MICP_MIC_CTLR
    #define CONFIG_BT_MICP_MIC_CTLR BT_MICP_MIC_CTLR
#endif

//BT_MICP_MIC_DEV
#ifdef BT_MICP_MIC_DEV
    #define CONFIG_BT_MICP_MIC_DEV BT_MICP_MIC_DEV
#endif

//BT_MICP_MIC_DEV_AICS
#ifdef BT_MICP_MIC_DEV_AICS
    #define CONFIG_BT_MICP_MIC_DEV_AICS BT_MICP_MIC_DEV_AICS
#endif

//BT_MICP_MIC_DEV_AICS_INSTANCE_COUNT
#ifdef BT_MICP_MIC_DEV_AICS_INSTANCE_COUNT
    #define CONFIG_BT_MICP_MIC_DEV_AICS_INSTANCE_COUNT BT_MICP_MIC_DEV_AICS_INSTANCE_COUNT
#endif

//BT_MPL
#ifdef BT_MPL
    #define CONFIG_BT_MPL BT_MPL
#endif

//BT_MPL_GROUP_TITLE_MAX
#ifdef BT_MPL_GROUP_TITLE_MAX
    #define CONFIG_BT_MPL_GROUP_TITLE_MAX BT_MPL_GROUP_TITLE_MAX
#endif

//BT_MPL_ICON_URL
#ifdef BT_MPL_ICON_URL
    #define CONFIG_BT_MPL_ICON_URL BT_MPL_ICON_URL
#endif

//BT_MPL_ICON_URL_MAX
#ifdef BT_MPL_ICON_URL_MAX
    #define CONFIG_BT_MPL_ICON_URL_MAX BT_MPL_ICON_URL_MAX
#endif

//BT_MPL_MEDIA_PLAYER_NAME
#ifdef BT_MPL_MEDIA_PLAYER_NAME
    #define CONFIG_BT_MPL_MEDIA_PLAYER_NAME BT_MPL_MEDIA_PLAYER_NAME
#endif

//BT_MPL_MEDIA_PLAYER_NAME_MAX
#ifdef BT_MPL_MEDIA_PLAYER_NAME_MAX
    #define CONFIG_BT_MPL_MEDIA_PLAYER_NAME_MAX BT_MPL_MEDIA_PLAYER_NAME_MAX
#endif

//BT_MPL_SEGMENT_NAME_MAX
#ifdef BT_MPL_SEGMENT_NAME_MAX
    #define CONFIG_BT_MPL_SEGMENT_NAME_MAX BT_MPL_SEGMENT_NAME_MAX
#endif

//BT_MPL_TRACK_TITLE_MAX
#ifdef BT_MPL_TRACK_TITLE_MAX
    #define CONFIG_BT_MPL_TRACK_TITLE_MAX BT_MPL_TRACK_TITLE_MAX
#endif

//BT_OBSERVER
#ifdef BT_OBSERVER
    #define CONFIG_BT_OBSERVER BT_OBSERVER
#endif

//BT_OTS
#ifdef BT_OTS
    #define CONFIG_BT_OTS BT_OTS
#endif

//BT_OTS_CLIENT
#ifdef BT_OTS_CLIENT
    #define CONFIG_BT_OTS_CLIENT BT_OTS_CLIENT
#endif

//BT_OTS_DIR_LIST_OBJ
#ifdef BT_OTS_DIR_LIST_OBJ
    #define CONFIG_BT_OTS_DIR_LIST_OBJ BT_OTS_DIR_LIST_OBJ
#endif

//BT_OTS_DIR_LIST_OBJ_NAME
#ifdef BT_OTS_DIR_LIST_OBJ_NAME
    #define CONFIG_BT_OTS_DIR_LIST_OBJ_NAME BT_OTS_DIR_LIST_OBJ_NAME
#endif

//BT_OTS_L2CAP_CHAN_RX_MTU
#ifdef BT_OTS_L2CAP_CHAN_RX_MTU
    #define CONFIG_BT_OTS_L2CAP_CHAN_RX_MTU BT_OTS_L2CAP_CHAN_RX_MTU
#endif

//BT_OTS_L2CAP_CHAN_TX_MTU
#ifdef BT_OTS_L2CAP_CHAN_TX_MTU
    #define CONFIG_BT_OTS_L2CAP_CHAN_TX_MTU BT_OTS_L2CAP_CHAN_TX_MTU
#endif

//BT_OTS_MAX_INST_CNT
#ifdef BT_OTS_MAX_INST_CNT
    #define CONFIG_BT_OTS_MAX_INST_CNT BT_OTS_MAX_INST_CNT
#endif

//BT_OTS_MAX_OBJ_CNT
#ifdef BT_OTS_MAX_OBJ_CNT
    #define CONFIG_BT_OTS_MAX_OBJ_CNT BT_OTS_MAX_OBJ_CNT
#endif

//BT_OTS_OACP_CHECKSUM_SUPPORT
#ifdef BT_OTS_OACP_CHECKSUM_SUPPORT
    #define CONFIG_BT_OTS_OACP_CHECKSUM_SUPPORT BT_OTS_OACP_CHECKSUM_SUPPORT
#endif

//BT_OTS_OACP_CREATE_SUPPORT
#ifdef BT_OTS_OACP_CREATE_SUPPORT
    #define CONFIG_BT_OTS_OACP_CREATE_SUPPORT BT_OTS_OACP_CREATE_SUPPORT
#endif

//BT_OTS_OACP_DELETE_SUPPORT
#ifdef BT_OTS_OACP_DELETE_SUPPORT
    #define CONFIG_BT_OTS_OACP_DELETE_SUPPORT BT_OTS_OACP_DELETE_SUPPORT
#endif

//BT_OTS_OACP_PATCH_SUPPORT
#ifdef BT_OTS_OACP_PATCH_SUPPORT
    #define CONFIG_BT_OTS_OACP_PATCH_SUPPORT BT_OTS_OACP_PATCH_SUPPORT
#endif

//BT_OTS_OACP_READ_SUPPORT
#ifdef BT_OTS_OACP_READ_SUPPORT
    #define CONFIG_BT_OTS_OACP_READ_SUPPORT BT_OTS_OACP_READ_SUPPORT
#endif

//BT_OTS_OACP_WRITE_SUPPORT
#ifdef BT_OTS_OACP_WRITE_SUPPORT
    #define CONFIG_BT_OTS_OACP_WRITE_SUPPORT BT_OTS_OACP_WRITE_SUPPORT
#endif

//BT_OTS_OBJ_MAX_NAME_LEN
#ifdef BT_OTS_OBJ_MAX_NAME_LEN
    #define CONFIG_BT_OTS_OBJ_MAX_NAME_LEN BT_OTS_OBJ_MAX_NAME_LEN
#endif

//BT_OTS_OBJ_NAME_WRITE_SUPPORT
#ifdef BT_OTS_OBJ_NAME_WRITE_SUPPORT
    #define CONFIG_BT_OTS_OBJ_NAME_WRITE_SUPPORT BT_OTS_OBJ_NAME_WRITE_SUPPORT
#endif

//BT_OTS_OLCP_GO_TO_SUPPORT
#ifdef BT_OTS_OLCP_GO_TO_SUPPORT
    #define CONFIG_BT_OTS_OLCP_GO_TO_SUPPORT BT_OTS_OLCP_GO_TO_SUPPORT
#endif

//BT_OTS_SECONDARY_SVC
#ifdef BT_OTS_SECONDARY_SVC
    #define CONFIG_BT_OTS_SECONDARY_SVC BT_OTS_SECONDARY_SVC
#endif

//BT_PACS
#ifdef BT_PACS
    #define CONFIG_BT_PACS BT_PACS
#endif

//BT_PACS_SUPPORTED_CONTEXT_NOTIFIABLE
#ifdef BT_PACS_SUPPORTED_CONTEXT_NOTIFIABLE
    #define CONFIG_BT_PACS_SUPPORTED_CONTEXT_NOTIFIABLE BT_PACS_SUPPORTED_CONTEXT_NOTIFIABLE
#endif

//BT_PAC_SNK2
#ifdef BT_PAC_SNK2
    #define CONFIG_BT_PAC_SNK BT_PAC_SNK2
#endif

//BT_PAC_SNK_LOC
#ifdef BT_PAC_SNK_LOC
    #define CONFIG_BT_PAC_SNK_LOC BT_PAC_SNK_LOC
#endif

//BT_PAC_SNK_LOC_NOTIFIABLE
#ifdef BT_PAC_SNK_LOC_NOTIFIABLE
    #define CONFIG_BT_PAC_SNK_LOC_NOTIFIABLE BT_PAC_SNK_LOC_NOTIFIABLE
#endif

//BT_PAC_SNK_LOC_WRITEABLE
#ifdef BT_PAC_SNK_LOC_WRITEABLE
    #define CONFIG_BT_PAC_SNK_LOC_WRITEABLE BT_PAC_SNK_LOC_WRITEABLE
#endif

//BT_PAC_SNK_NOTIFIABLE
#ifdef BT_PAC_SNK_NOTIFIABLE
    #define CONFIG_BT_PAC_SNK_NOTIFIABLE BT_PAC_SNK_NOTIFIABLE
#endif

//BT_PAC_SRC2
#ifdef BT_PAC_SRC2
    #define CONFIG_BT_PAC_SRC BT_PAC_SRC2
#endif

//BT_PAC_SRC_LOC
#ifdef BT_PAC_SRC_LOC
    #define CONFIG_BT_PAC_SRC_LOC BT_PAC_SRC_LOC
#endif

//BT_PAC_SRC_LOC_NOTIFIABLE
#ifdef BT_PAC_SRC_LOC_NOTIFIABLE
    #define CONFIG_BT_PAC_SRC_LOC_NOTIFIABLE BT_PAC_SRC_LOC_NOTIFIABLE
#endif

//BT_PAC_SRC_LOC_WRITEABLE
#ifdef BT_PAC_SRC_LOC_WRITEABLE
    #define CONFIG_BT_PAC_SRC_LOC_WRITEABLE BT_PAC_SRC_LOC_WRITEABLE
#endif

//BT_PAC_SRC_NOTIFIABLE
#ifdef BT_PAC_SRC_NOTIFIABLE
    #define CONFIG_BT_PAC_SRC_NOTIFIABLE BT_PAC_SRC_NOTIFIABLE
#endif

//BT_PASSKEY_KEYPRESS
#ifdef BT_PASSKEY_KEYPRESS
    #define CONFIG_BT_PASSKEY_KEYPRESS BT_PASSKEY_KEYPRESS
#endif

//BT_PATH_LOSS_MONITORING
#ifdef BT_PATH_LOSS_MONITORING
    #define CONFIG_BT_PATH_LOSS_MONITORING BT_PATH_LOSS_MONITORING
#endif

//BT_PBP
#ifdef BT_PBP
    #define CONFIG_BT_PBP BT_PBP
#endif

//BT_PERIPHERAL
#ifdef BT_PERIPHERAL
    #define CONFIG_BT_PERIPHERAL BT_PERIPHERAL
#endif

//BT_PERIPHERAL_PREF_LATENCY
#ifdef BT_PERIPHERAL_PREF_LATENCY
    #define CONFIG_BT_PERIPHERAL_PREF_LATENCY BT_PERIPHERAL_PREF_LATENCY
#endif

//BT_PERIPHERAL_PREF_MAX_INT
#ifdef BT_PERIPHERAL_PREF_MAX_INT
    #define CONFIG_BT_PERIPHERAL_PREF_MAX_INT BT_PERIPHERAL_PREF_MAX_INT
#endif

//BT_PERIPHERAL_PREF_MIN_INT
#ifdef BT_PERIPHERAL_PREF_MIN_INT
    #define CONFIG_BT_PERIPHERAL_PREF_MIN_INT BT_PERIPHERAL_PREF_MIN_INT
#endif

//BT_PERIPHERAL_PREF_TIMEOUT
#ifdef BT_PERIPHERAL_PREF_TIMEOUT
    #define CONFIG_BT_PERIPHERAL_PREF_TIMEOUT BT_PERIPHERAL_PREF_TIMEOUT
#endif

//BT_PER_ADV
#ifdef BT_PER_ADV
    #define CONFIG_BT_PER_ADV BT_PER_ADV
#endif

//BT_PER_ADV_RSP
#ifdef BT_PER_ADV_RSP
    #define CONFIG_BT_PER_ADV_RSP BT_PER_ADV_RSP
#endif

//BT_PER_ADV_SYNC
#ifdef BT_PER_ADV_SYNC
    #define CONFIG_BT_PER_ADV_SYNC BT_PER_ADV_SYNC
#endif

//BT_PER_ADV_SYNC_BUF_SIZE
#ifdef BT_PER_ADV_SYNC_BUF_SIZE
    #define CONFIG_BT_PER_ADV_SYNC_BUF_SIZE BT_PER_ADV_SYNC_BUF_SIZE
#endif

//BT_PER_ADV_SYNC_MAX
#ifdef BT_PER_ADV_SYNC_MAX
    #define CONFIG_BT_PER_ADV_SYNC_MAX BT_PER_ADV_SYNC_MAX
#endif

//BT_PER_ADV_SYNC_RSP
#ifdef BT_PER_ADV_SYNC_RSP
    #define CONFIG_BT_PER_ADV_SYNC_RSP BT_PER_ADV_SYNC_RSP
#endif

//BT_PER_ADV_SYNC_TRANSFER_RECEIVER
#ifdef BT_PER_ADV_SYNC_TRANSFER_RECEIVER
    #define CONFIG_BT_PER_ADV_SYNC_TRANSFER_RECEIVER BT_PER_ADV_SYNC_TRANSFER_RECEIVER
#endif

//BT_PER_ADV_SYNC_TRANSFER_SENDER
#ifdef BT_PER_ADV_SYNC_TRANSFER_SENDER
    #define CONFIG_BT_PER_ADV_SYNC_TRANSFER_SENDER BT_PER_ADV_SYNC_TRANSFER_SENDER
#endif

//BT_PHY_UPDATE
#ifdef BT_PHY_UPDATE
    #define CONFIG_BT_PHY_UPDATE BT_PHY_UPDATE
#endif

//BT_PRIVACY
#ifdef BT_PRIVACY
    #define CONFIG_BT_PRIVACY BT_PRIVACY
#endif

//BT_PRIVACY_RANDOMIZE_IR
#ifdef BT_PRIVACY_RANDOMIZE_IR
    #define CONFIG_BT_PRIVACY_RANDOMIZE_IR BT_PRIVACY_RANDOMIZE_IR
#endif

//BT_RECV_WORKQ_BT
#ifdef BT_RECV_WORKQ_BT
    #define CONFIG_BT_RECV_WORKQ_BT BT_RECV_WORKQ_BT
#endif

//BT_RECV_WORKQ_SYS
#ifdef BT_RECV_WORKQ_SYS
    #define CONFIG_BT_RECV_WORKQ_SYS BT_RECV_WORKQ_SYS
#endif

//BT_REMOTE_INFO
#ifdef BT_REMOTE_INFO
    #define CONFIG_BT_REMOTE_INFO BT_REMOTE_INFO
#endif

//BT_REMOTE_VERSION
#ifdef BT_REMOTE_VERSION
    #define CONFIG_BT_REMOTE_VERSION BT_REMOTE_VERSION
#endif

//BT_RPA
#ifdef BT_RPA
    #define CONFIG_BT_RPA BT_RPA
#endif

//BT_RPA_SHARING
#ifdef BT_RPA_SHARING
    #define CONFIG_BT_RPA_SHARING BT_RPA_SHARING
#endif

//BT_RPA_TIMEOUT
#ifdef BT_RPA_TIMEOUT
    #define CONFIG_BT_RPA_TIMEOUT BT_RPA_TIMEOUT
#endif

//BT_RPA_TIMEOUT_DYNAMIC
#ifdef BT_RPA_TIMEOUT_DYNAMIC
    #define CONFIG_BT_RPA_TIMEOUT_DYNAMIC BT_RPA_TIMEOUT_DYNAMIC
#endif

//BT_RX_PRIO
#ifdef BT_RX_PRIO
    #define CONFIG_BT_RX_PRIO BT_RX_PRIO

    #ifndef BT_TX_PRIO
        #define BT_TX_PRIO BT_RX_PRIO
    #endif

    #ifdef BT_TX_PRIO
        #define CONFIG_BT_TX_PRIO BT_TX_PRIO
    #endif

#endif

//BT_RX_STACK_SIZE
#ifdef BT_RX_STACK_SIZE
    #define CONFIG_BT_RX_STACK_SIZE BT_RX_STACK_SIZE

    // reuse rx define
    #ifndef BT_TX_STACK_SIZE
        #define BT_TX_STACK_SIZE BT_RX_STACK_SIZE
    #endif

    #ifdef BT_TX_STACK_SIZE
        #define CONFIG_BT_TX_STACK_SIZE BT_TX_STACK_SIZE
    #endif
#endif


//BT_SCAN_AND_INITIATE_IN_PARALLEL
#ifdef BT_SCAN_AND_INITIATE_IN_PARALLEL
    #define CONFIG_BT_SCAN_AND_INITIATE_IN_PARALLEL BT_SCAN_AND_INITIATE_IN_PARALLEL
#endif

//BT_SCAN_WITH_IDENTITY
#ifdef BT_SCAN_WITH_IDENTITY
    #define CONFIG_BT_SCAN_WITH_IDENTITY BT_SCAN_WITH_IDENTITY
#endif

//BT_SCA_UPDATE
#ifdef BT_SCA_UPDATE
    #define CONFIG_BT_SCA_UPDATE BT_SCA_UPDATE
#endif

//BT_SECURITY_ERR_TO_STR
#ifdef BT_SECURITY_ERR_TO_STR
    #define CONFIG_BT_SECURITY_ERR_TO_STR BT_SECURITY_ERR_TO_STR
#endif

//BT_SETTINGS
#ifdef BT_SETTINGS
    #define CONFIG_BT_SETTINGS BT_SETTINGS
#endif

//BT_SETTINGS_CCC_LAZY_LOADING
#ifdef BT_SETTINGS_CCC_LAZY_LOADING
    #define CONFIG_BT_SETTINGS_CCC_LAZY_LOADING BT_SETTINGS_CCC_LAZY_LOADING
#endif

//BT_SETTINGS_CCC_STORE_MAX
#ifdef BT_SETTINGS_CCC_STORE_MAX
    #define CONFIG_BT_SETTINGS_CCC_STORE_MAX BT_SETTINGS_CCC_STORE_MAX
#endif

//BT_SETTINGS_CCC_STORE_ON_WRITE
#ifdef BT_SETTINGS_CCC_STORE_ON_WRITE
    #define CONFIG_BT_SETTINGS_CCC_STORE_ON_WRITE BT_SETTINGS_CCC_STORE_ON_WRITE
#endif

//BT_SETTINGS_CF_STORE_ON_WRITE
#ifdef BT_SETTINGS_CF_STORE_ON_WRITE
    #define CONFIG_BT_SETTINGS_CF_STORE_ON_WRITE BT_SETTINGS_CF_STORE_ON_WRITE
#endif

//BT_SETTINGS_DELAYED_STORE
#ifdef BT_SETTINGS_DELAYED_STORE
    #define CONFIG_BT_SETTINGS_DELAYED_STORE BT_SETTINGS_DELAYED_STORE
#endif

//BT_SETTINGS_DELAYED_STORE_MS
#ifdef BT_SETTINGS_DELAYED_STORE_MS
    #define CONFIG_BT_SETTINGS_DELAYED_STORE_MS BT_SETTINGS_DELAYED_STORE_MS
#endif

//BT_SHELL
#ifdef BT_SHELL
    #define CONFIG_BT_SHELL BT_SHELL
#endif

//BT_SIGNING
#ifdef BT_SIGNING
    #define CONFIG_BT_SIGNING BT_SIGNING
#endif

//BT_SMP
#ifdef BT_SMP
    #define CONFIG_BT_SMP BT_SMP
#endif

//BT_SMP_ALLOW_UNAUTH_OVERWRITE
#ifdef BT_SMP_ALLOW_UNAUTH_OVERWRITE
    #define CONFIG_BT_SMP_ALLOW_UNAUTH_OVERWRITE BT_SMP_ALLOW_UNAUTH_OVERWRITE
#endif

//BT_SMP_APP_PAIRING_ACCEPT
#ifdef BT_SMP_APP_PAIRING_ACCEPT
    #define CONFIG_BT_SMP_APP_PAIRING_ACCEPT BT_SMP_APP_PAIRING_ACCEPT
#endif

//BT_SMP_DISABLE_LEGACY_JW_PASSKEY
#ifdef BT_SMP_DISABLE_LEGACY_JW_PASSKEY
    #define CONFIG_BT_SMP_DISABLE_LEGACY_JW_PASSKEY BT_SMP_DISABLE_LEGACY_JW_PASSKEY
#endif

//BT_SMP_ENFORCE_MITM
#ifdef BT_SMP_ENFORCE_MITM
    #define CONFIG_BT_SMP_ENFORCE_MITM BT_SMP_ENFORCE_MITM
#endif

//BT_SMP_ERR_TO_STR
#ifdef BT_SMP_ERR_TO_STR
    #define CONFIG_BT_SMP_ERR_TO_STR BT_SMP_ERR_TO_STR
#endif

//BT_SMP_MIN_ENC_KEY_SIZE
#ifdef BT_SMP_MIN_ENC_KEY_SIZE
    #define CONFIG_BT_SMP_MIN_ENC_KEY_SIZE BT_SMP_MIN_ENC_KEY_SIZE
#endif

//BT_SMP_OOB_LEGACY_PAIR_ONLY
#ifdef BT_SMP_OOB_LEGACY_PAIR_ONLY
    #define CONFIG_BT_SMP_OOB_LEGACY_PAIR_ONLY BT_SMP_OOB_LEGACY_PAIR_ONLY
#endif

//BT_SMP_SC_ONLY
#ifdef BT_SMP_SC_ONLY
    #define CONFIG_BT_SMP_SC_ONLY BT_SMP_SC_ONLY
#endif

//BT_SMP_SC_PAIR_ONLY
#ifdef BT_SMP_SC_PAIR_ONLY
    #define CONFIG_BT_SMP_SC_PAIR_ONLY BT_SMP_SC_PAIR_ONLY
#endif

//BT_STORE_DEBUG_KEYS
#ifdef BT_STORE_DEBUG_KEYS
    #define CONFIG_BT_STORE_DEBUG_KEYS BT_STORE_DEBUG_KEYS
#endif

//BT_SUBRATING
#ifdef BT_SUBRATING
    #define CONFIG_BT_SUBRATING BT_SUBRATING
#endif

//BT_TBS
#ifdef BT_TBS
    #define CONFIG_BT_TBS BT_TBS
#endif

//BT_TBS_BEARER_COUNT
#ifdef BT_TBS_BEARER_COUNT
    #define CONFIG_BT_TBS_BEARER_COUNT BT_TBS_BEARER_COUNT
#endif

//BT_TBS_CLIENT
#ifdef BT_TBS_CLIENT
    #define CONFIG_BT_TBS_CLIENT BT_TBS_CLIENT
#endif

//BT_TBS_CLIENT_ACCEPT_CALL
#ifdef BT_TBS_CLIENT_ACCEPT_CALL
    #define CONFIG_BT_TBS_CLIENT_ACCEPT_CALL BT_TBS_CLIENT_ACCEPT_CALL
#endif

//BT_TBS_CLIENT_BEARER_LIST_CURRENT_CALLS
#ifdef BT_TBS_CLIENT_BEARER_LIST_CURRENT_CALLS
    #define CONFIG_BT_TBS_CLIENT_BEARER_LIST_CURRENT_CALLS BT_TBS_CLIENT_BEARER_LIST_CURRENT_CALLS
#endif

//BT_TBS_CLIENT_BEARER_PROVIDER_NAME
#ifdef BT_TBS_CLIENT_BEARER_PROVIDER_NAME
    #define CONFIG_BT_TBS_CLIENT_BEARER_PROVIDER_NAME BT_TBS_CLIENT_BEARER_PROVIDER_NAME
#endif

//BT_TBS_CLIENT_BEARER_SIGNAL_STRENGTH
#ifdef BT_TBS_CLIENT_BEARER_SIGNAL_STRENGTH
    #define CONFIG_BT_TBS_CLIENT_BEARER_SIGNAL_STRENGTH BT_TBS_CLIENT_BEARER_SIGNAL_STRENGTH
#endif

//BT_TBS_CLIENT_BEARER_TECHNOLOGY
#ifdef BT_TBS_CLIENT_BEARER_TECHNOLOGY
    #define CONFIG_BT_TBS_CLIENT_BEARER_TECHNOLOGY BT_TBS_CLIENT_BEARER_TECHNOLOGY
#endif

//BT_TBS_CLIENT_BEARER_UCI
#ifdef BT_TBS_CLIENT_BEARER_UCI
    #define CONFIG_BT_TBS_CLIENT_BEARER_UCI BT_TBS_CLIENT_BEARER_UCI
#endif

//BT_TBS_CLIENT_BEARER_URI_SCHEMES_SUPPORTED_LIST
#ifdef BT_TBS_CLIENT_BEARER_URI_SCHEMES_SUPPORTED_LIST
    #define CONFIG_BT_TBS_CLIENT_BEARER_URI_SCHEMES_SUPPORTED_LIST BT_TBS_CLIENT_BEARER_URI_SCHEMES_SUPPORTED_LIST
#endif

//BT_TBS_CLIENT_CALL_FRIENDLY_NAME
#ifdef BT_TBS_CLIENT_CALL_FRIENDLY_NAME
    #define CONFIG_BT_TBS_CLIENT_CALL_FRIENDLY_NAME BT_TBS_CLIENT_CALL_FRIENDLY_NAME
#endif

//BT_TBS_CLIENT_CCID
#ifdef BT_TBS_CLIENT_CCID
    #define CONFIG_BT_TBS_CLIENT_CCID BT_TBS_CLIENT_CCID
#endif

//BT_TBS_CLIENT_CP_PROCEDURES
#ifdef BT_TBS_CLIENT_CP_PROCEDURES
    #define CONFIG_BT_TBS_CLIENT_CP_PROCEDURES BT_TBS_CLIENT_CP_PROCEDURES
#endif

//BT_TBS_CLIENT_GTBS
#ifdef BT_TBS_CLIENT_GTBS
    #define CONFIG_BT_TBS_CLIENT_GTBS BT_TBS_CLIENT_GTBS
#endif

//BT_TBS_CLIENT_HOLD_CALL
#ifdef BT_TBS_CLIENT_HOLD_CALL
    #define CONFIG_BT_TBS_CLIENT_HOLD_CALL BT_TBS_CLIENT_HOLD_CALL
#endif

//BT_TBS_CLIENT_INCOMING_CALL
#ifdef BT_TBS_CLIENT_INCOMING_CALL
    #define CONFIG_BT_TBS_CLIENT_INCOMING_CALL BT_TBS_CLIENT_INCOMING_CALL
#endif

//BT_TBS_CLIENT_INCOMING_URI
#ifdef BT_TBS_CLIENT_INCOMING_URI
    #define CONFIG_BT_TBS_CLIENT_INCOMING_URI BT_TBS_CLIENT_INCOMING_URI
#endif

//BT_TBS_CLIENT_MAX_CALLS
#ifdef BT_TBS_CLIENT_MAX_CALLS
    #define CONFIG_BT_TBS_CLIENT_MAX_CALLS BT_TBS_CLIENT_MAX_CALLS
#endif

//BT_TBS_CLIENT_MAX_TBS_INSTANCES
#ifdef BT_TBS_CLIENT_MAX_TBS_INSTANCES
    #define CONFIG_BT_TBS_CLIENT_MAX_TBS_INSTANCES BT_TBS_CLIENT_MAX_TBS_INSTANCES
#endif

//BT_TBS_CLIENT_MINIMAL
#ifdef BT_TBS_CLIENT_MINIMAL
    #define CONFIG_BT_TBS_CLIENT_MINIMAL BT_TBS_CLIENT_MINIMAL
#endif

//BT_TBS_CLIENT_OPTIONAL_OPCODES
#ifdef BT_TBS_CLIENT_OPTIONAL_OPCODES
    #define CONFIG_BT_TBS_CLIENT_OPTIONAL_OPCODES BT_TBS_CLIENT_OPTIONAL_OPCODES
#endif

//BT_TBS_CLIENT_ORIGINATE_CALL
#ifdef BT_TBS_CLIENT_ORIGINATE_CALL
    #define CONFIG_BT_TBS_CLIENT_ORIGINATE_CALL BT_TBS_CLIENT_ORIGINATE_CALL
#endif

//BT_TBS_CLIENT_READ_BEARER_SIGNAL_INTERVAL
#ifdef BT_TBS_CLIENT_READ_BEARER_SIGNAL_INTERVAL
    #define CONFIG_BT_TBS_CLIENT_READ_BEARER_SIGNAL_INTERVAL BT_TBS_CLIENT_READ_BEARER_SIGNAL_INTERVAL
#endif

//BT_TBS_CLIENT_RETRIEVE_CALL
#ifdef BT_TBS_CLIENT_RETRIEVE_CALL
    #define CONFIG_BT_TBS_CLIENT_RETRIEVE_CALL BT_TBS_CLIENT_RETRIEVE_CALL
#endif

//BT_TBS_CLIENT_SET_BEARER_SIGNAL_INTERVAL
#ifdef BT_TBS_CLIENT_SET_BEARER_SIGNAL_INTERVAL
    #define CONFIG_BT_TBS_CLIENT_SET_BEARER_SIGNAL_INTERVAL BT_TBS_CLIENT_SET_BEARER_SIGNAL_INTERVAL
#endif

//BT_TBS_CLIENT_STATUS_FLAGS
#ifdef BT_TBS_CLIENT_STATUS_FLAGS
    #define CONFIG_BT_TBS_CLIENT_STATUS_FLAGS BT_TBS_CLIENT_STATUS_FLAGS
#endif

//BT_TBS_CLIENT_TBS
#ifdef BT_TBS_CLIENT_TBS
    #define CONFIG_BT_TBS_CLIENT_TBS BT_TBS_CLIENT_TBS
#endif

//BT_TBS_CLIENT_TERMINATE_CALL
#ifdef BT_TBS_CLIENT_TERMINATE_CALL
    #define CONFIG_BT_TBS_CLIENT_TERMINATE_CALL BT_TBS_CLIENT_TERMINATE_CALL
#endif

//BT_TBS_MAX_CALLS
#ifdef BT_TBS_MAX_CALLS
    #define CONFIG_BT_TBS_MAX_CALLS BT_TBS_MAX_CALLS
#endif

//BT_TBS_MAX_PROVIDER_NAME_LENGTH
#ifdef BT_TBS_MAX_PROVIDER_NAME_LENGTH
    #define CONFIG_BT_TBS_MAX_PROVIDER_NAME_LENGTH BT_TBS_MAX_PROVIDER_NAME_LENGTH
#endif

//BT_TBS_MAX_SCHEME_LIST_LENGTH
#ifdef BT_TBS_MAX_SCHEME_LIST_LENGTH
    #define CONFIG_BT_TBS_MAX_SCHEME_LIST_LENGTH BT_TBS_MAX_SCHEME_LIST_LENGTH
#endif

//BT_TBS_MAX_URI_LENGTH
#ifdef BT_TBS_MAX_URI_LENGTH
    #define CONFIG_BT_TBS_MAX_URI_LENGTH BT_TBS_MAX_URI_LENGTH
#endif

//BT_TBS_SUPPORTED_FEATURES
#ifdef BT_TBS_SUPPORTED_FEATURES
    #define CONFIG_BT_TBS_SUPPORTED_FEATURES BT_TBS_SUPPORTED_FEATURES
#endif

//BT_TESTING
#ifdef BT_TESTING
    #define CONFIG_BT_TESTING BT_TESTING
#endif

//BT_TINYCRYPT_ECC
#ifdef BT_TINYCRYPT_ECC
    #define CONFIG_BT_TINYCRYPT_ECC BT_TINYCRYPT_ECC
#endif

//BT_TMAP
#ifdef BT_TMAP
    #define CONFIG_BT_TMAP BT_TMAP
#endif

//BT_TPS
#ifdef BT_TPS
    #define CONFIG_BT_TPS BT_TPS
#endif

//BT_TRANSMIT_POWER_CONTROL
#ifdef BT_TRANSMIT_POWER_CONTROL
    #define CONFIG_BT_TRANSMIT_POWER_CONTROL BT_TRANSMIT_POWER_CONTROL
#endif

//BT_USER_DATA_LEN_UPDATE
#ifdef BT_USER_DATA_LEN_UPDATE
    #define CONFIG_BT_USER_DATA_LEN_UPDATE BT_USER_DATA_LEN_UPDATE
#endif

//BT_USER_PHY_UPDATE
#ifdef BT_USER_PHY_UPDATE
    #define CONFIG_BT_USER_PHY_UPDATE BT_USER_PHY_UPDATE
#endif

//BT_USE_DEBUG_KEYS
#ifdef BT_USE_DEBUG_KEYS
    #define CONFIG_BT_USE_DEBUG_KEYS BT_USE_DEBUG_KEYS
#endif

//BT_USE_PSA_API
#ifdef BT_USE_PSA_API
    #define CONFIG_BT_USE_PSA_API BT_USE_PSA_API
#endif

//BT_VCP_VOL_CTLR
#ifdef BT_VCP_VOL_CTLR
    #define CONFIG_BT_VCP_VOL_CTLR BT_VCP_VOL_CTLR
#endif

//BT_VCP_VOL_CTLR_MAX_AICS_INST
#ifdef BT_VCP_VOL_CTLR_MAX_AICS_INST
    #define CONFIG_BT_VCP_VOL_CTLR_MAX_AICS_INST BT_VCP_VOL_CTLR_MAX_AICS_INST
#endif

//BT_VCP_VOL_CTLR_MAX_VOCS_INST
#ifdef BT_VCP_VOL_CTLR_MAX_VOCS_INST
    #define CONFIG_BT_VCP_VOL_CTLR_MAX_VOCS_INST BT_VCP_VOL_CTLR_MAX_VOCS_INST
#endif

//BT_VCP_VOL_REND
#ifdef BT_VCP_VOL_REND
    #define CONFIG_BT_VCP_VOL_REND BT_VCP_VOL_REND
#endif

//BT_VCP_VOL_REND_AICS
#ifdef BT_VCP_VOL_REND_AICS
    #define CONFIG_BT_VCP_VOL_REND_AICS BT_VCP_VOL_REND_AICS
#endif

//BT_VCP_VOL_REND_AICS_INSTANCE_COUNT
#ifdef BT_VCP_VOL_REND_AICS_INSTANCE_COUNT
    #define CONFIG_BT_VCP_VOL_REND_AICS_INSTANCE_COUNT BT_VCP_VOL_REND_AICS_INSTANCE_COUNT
#endif

//BT_VCP_VOL_REND_VOCS
#ifdef BT_VCP_VOL_REND_VOCS
    #define CONFIG_BT_VCP_VOL_REND_VOCS BT_VCP_VOL_REND_VOCS
#endif

//BT_VCP_VOL_REND_VOCS_INSTANCE_COUNT
#ifdef BT_VCP_VOL_REND_VOCS_INSTANCE_COUNT
    #define CONFIG_BT_VCP_VOL_REND_VOCS_INSTANCE_COUNT BT_VCP_VOL_REND_VOCS_INSTANCE_COUNT
#endif

//BT_VCP_VOL_REND_VOL_FLAGS_NOTIFIABLE
#ifdef BT_VCP_VOL_REND_VOL_FLAGS_NOTIFIABLE
    #define CONFIG_BT_VCP_VOL_REND_VOL_FLAGS_NOTIFIABLE BT_VCP_VOL_REND_VOL_FLAGS_NOTIFIABLE
#endif

//BT_VOCS
#ifdef BT_VOCS
    #define CONFIG_BT_VOCS BT_VOCS
#endif

//BT_VOCS_CLIENT_MAX_INSTANCE_COUNT
#ifdef BT_VOCS_CLIENT_MAX_INSTANCE_COUNT
    #define CONFIG_BT_VOCS_CLIENT_MAX_INSTANCE_COUNT BT_VOCS_CLIENT_MAX_INSTANCE_COUNT
#endif

//BT_VOCS_MAX_INSTANCE_COUNT
#ifdef BT_VOCS_MAX_INSTANCE_COUNT
    #define CONFIG_BT_VOCS_MAX_INSTANCE_COUNT BT_VOCS_MAX_INSTANCE_COUNT
#endif

//BT_VOCS_MAX_OUTPUT_DESCRIPTION_SIZE
#ifdef BT_VOCS_MAX_OUTPUT_DESCRIPTION_SIZE
    #define CONFIG_BT_VOCS_MAX_OUTPUT_DESCRIPTION_SIZE BT_VOCS_MAX_OUTPUT_DESCRIPTION_SIZE
#endif

//BT_WAIT_NOP
#ifdef BT_WAIT_NOP
    #define CONFIG_BT_WAIT_NOP BT_WAIT_NOP
#endif

//BT_ZEPHYR_NUS
#ifdef BT_ZEPHYR_NUS
    #define CONFIG_BT_ZEPHYR_NUS BT_ZEPHYR_NUS
#endif

//BT_ZEPHYR_NUS_DEFAULT_INSTANCE
#ifdef BT_ZEPHYR_NUS_DEFAULT_INSTANCE
    #define CONFIG_BT_ZEPHYR_NUS_DEFAULT_INSTANCE BT_ZEPHYR_NUS_DEFAULT_INSTANCE
#endif

//DEVICE_NAME_GATT_WRITABLE_AUTHEN
#ifdef DEVICE_NAME_GATT_WRITABLE_AUTHEN
    #define CONFIG_DEVICE_NAME_GATT_WRITABLE_AUTHEN DEVICE_NAME_GATT_WRITABLE_AUTHEN
#endif

//DEVICE_NAME_GATT_WRITABLE_ENCRYPT
#ifdef DEVICE_NAME_GATT_WRITABLE_ENCRYPT
    #define CONFIG_DEVICE_NAME_GATT_WRITABLE_ENCRYPT DEVICE_NAME_GATT_WRITABLE_ENCRYPT
#endif

//DEVICE_NAME_GATT_WRITABLE_NONE
#ifdef DEVICE_NAME_GATT_WRITABLE_NONE
    #define CONFIG_DEVICE_NAME_GATT_WRITABLE_NONE DEVICE_NAME_GATT_WRITABLE_NONE
#endif

//ENABLE_LC3
#ifdef ENABLE_LC3
    #define CONFIG_ENABLE_LC3 ENABLE_LC3
#endif

//LIBLC3
#ifdef LIBLC3
    #define CONFIG_LIBLC3 LIBLC3
#endif

//MAX_CODEC_FRAMES_PER_SDU
#ifdef MAX_CODEC_FRAMES_PER_SDU
    #define CONFIG_MAX_CODEC_FRAMES_PER_SDU MAX_CODEC_FRAMES_PER_SDU
#endif

//MCTL
#ifdef MCTL
    #define CONFIG_MCTL MCTL
#endif

//MCTL_LOCAL_PLAYER_CONTROL
#ifdef MCTL_LOCAL_PLAYER_CONTROL
    #define CONFIG_MCTL_LOCAL_PLAYER_CONTROL MCTL_LOCAL_PLAYER_CONTROL
#endif

//MCTL_LOCAL_PLAYER_LOCAL_CONTROL
#ifdef MCTL_LOCAL_PLAYER_LOCAL_CONTROL
    #define CONFIG_MCTL_LOCAL_PLAYER_LOCAL_CONTROL MCTL_LOCAL_PLAYER_LOCAL_CONTROL
#endif

//MCTL_LOCAL_PLAYER_REMOTE_CONTROL
#ifdef MCTL_LOCAL_PLAYER_REMOTE_CONTROL
    #define CONFIG_MCTL_LOCAL_PLAYER_REMOTE_CONTROL MCTL_LOCAL_PLAYER_REMOTE_CONTROL
#endif

//PSA_CRYPTO_CLIENT
#ifdef PSA_CRYPTO_CLIENT
    #define CONFIG_PSA_CRYPTO_CLIENT PSA_CRYPTO_CLIENT
#endif

//SAMPLE_BROADCAST
#ifdef SAMPLE_BROADCAST
    #define CONFIG_SAMPLE_BROADCAST SAMPLE_BROADCAST
#endif

//SAMPLE_SCAN_SELF
#ifdef SAMPLE_SCAN_SELF
    #define CONFIG_SAMPLE_SCAN_SELF SAMPLE_SCAN_SELF
#endif

//SAMPLE_TARGET_BROADCAST_NAME
#ifdef SAMPLE_TARGET_BROADCAST_NAME
    #define CONFIG_SAMPLE_TARGET_BROADCAST_NAME SAMPLE_TARGET_BROADCAST_NAME
#endif

//SAMPLE_UNICAST
#ifdef SAMPLE_UNICAST
    #define CONFIG_SAMPLE_UNICAST SAMPLE_UNICAST
#endif

//SCAN_DELAY
#ifdef SCAN_DELAY
    #define CONFIG_SCAN_DELAY SCAN_DELAY
#endif

//SCAN_OFFLOAD
#ifdef SCAN_OFFLOAD
    #define CONFIG_SCAN_OFFLOAD SCAN_OFFLOAD
#endif

//SCAN_SELF
#ifdef SCAN_SELF
    #define CONFIG_SCAN_SELF SCAN_SELF
#endif

//SEGGER_RTT_MAX_NUM_UP_BUFFERS
#ifdef SEGGER_RTT_MAX_NUM_UP_BUFFERS
    #define CONFIG_SEGGER_RTT_MAX_NUM_UP_BUFFERS SEGGER_RTT_MAX_NUM_UP_BUFFERS
#endif

//SELECT_SINK_NAME
#ifdef SELECT_SINK_NAME
    #define CONFIG_SELECT_SINK_NAME SELECT_SINK_NAME
#endif

//SELECT_SOURCE_NAME
#ifdef SELECT_SOURCE_NAME
    #define CONFIG_SELECT_SOURCE_NAME SELECT_SOURCE_NAME
#endif

//SETTINGS
#ifdef SETTINGS
    #define CONFIG_SETTINGS SETTINGS
#endif

//SETTINGS_CUSTOM
#ifdef SETTINGS_CUSTOM
    #define CONFIG_SETTINGS_CUSTOM SETTINGS_CUSTOM
#endif

//SETTINGS_DYNAMIC_HANDLERS
#ifdef SETTINGS_DYNAMIC_HANDLERS
    #define CONFIG_SETTINGS_DYNAMIC_HANDLERS SETTINGS_DYNAMIC_HANDLERS
#endif

//SETTINGS_NONE
#ifdef SETTINGS_NONE
    #define CONFIG_SETTINGS_NONE SETTINGS_NONE
#endif

//SETTINGS_RUNTIME
#ifdef SETTINGS_RUNTIME
    #define CONFIG_SETTINGS_RUNTIME SETTINGS_RUNTIME
#endif

//SETTINGS_SIFLI
#ifdef SETTINGS_SIFLI
    #define CONFIG_SETTINGS_SIFLI SETTINGS_SIFLI
#endif

//TARGET_BROADCAST_NAME
#ifdef TARGET_BROADCAST_NAME
    #define CONFIG_TARGET_BROADCAST_NAME TARGET_BROADCAST_NAME
#endif

//TINYCRYPT
#ifdef TINYCRYPT
    #define CONFIG_TINYCRYPT TINYCRYPT
#endif

//TINYCRYPT_AES
#ifdef TINYCRYPT_AES
    #define CONFIG_TINYCRYPT_AES TINYCRYPT_AES
#endif

//TINYCRYPT_AES_CBC
#ifdef TINYCRYPT_AES_CBC
    #define CONFIG_TINYCRYPT_AES_CBC TINYCRYPT_AES_CBC
#endif

//TINYCRYPT_AES_CCM
#ifdef TINYCRYPT_AES_CCM
    #define CONFIG_TINYCRYPT_AES_CCM TINYCRYPT_AES_CCM
#endif

//TINYCRYPT_AES_CMAC
#ifdef TINYCRYPT_AES_CMAC
    #define CONFIG_TINYCRYPT_AES_CMAC TINYCRYPT_AES_CMAC
#endif

//TINYCRYPT_AES_CTR
#ifdef TINYCRYPT_AES_CTR
    #define CONFIG_TINYCRYPT_AES_CTR TINYCRYPT_AES_CTR
#endif

//TINYCRYPT_CTR_PRNG
#ifdef TINYCRYPT_CTR_PRNG
    #define CONFIG_TINYCRYPT_CTR_PRNG TINYCRYPT_CTR_PRNG
#endif

//TINYCRYPT_ECC_DH
#ifdef TINYCRYPT_ECC_DH
    #define CONFIG_TINYCRYPT_ECC_DH TINYCRYPT_ECC_DH
#endif

//TINYCRYPT_ECC_DSA
#ifdef TINYCRYPT_ECC_DSA
    #define CONFIG_TINYCRYPT_ECC_DSA TINYCRYPT_ECC_DSA
#endif

//TINYCRYPT_SHA256
#ifdef TINYCRYPT_SHA256
    #define CONFIG_TINYCRYPT_SHA256 TINYCRYPT_SHA256
#endif

//TINYCRYPT_SHA256_HMAC
#ifdef TINYCRYPT_SHA256_HMAC
    #define CONFIG_TINYCRYPT_SHA256_HMAC TINYCRYPT_SHA256_HMAC
#endif

//TINYCRYPT_SHA256_HMAC_PRNG
#ifdef TINYCRYPT_SHA256_HMAC_PRNG
    #define CONFIG_TINYCRYPT_SHA256_HMAC_PRNG TINYCRYPT_SHA256_HMAC_PRNG
#endif

//TMAP_PERIPHERAL_DUO
#ifdef TMAP_PERIPHERAL_DUO
    #define CONFIG_TMAP_PERIPHERAL_DUO TMAP_PERIPHERAL_DUO
#endif

//TMAP_PERIPHERAL_LEFT
#ifdef TMAP_PERIPHERAL_LEFT
    #define CONFIG_TMAP_PERIPHERAL_LEFT TMAP_PERIPHERAL_LEFT
#endif

//TMAP_PERIPHERAL_RIGHT
#ifdef TMAP_PERIPHERAL_RIGHT
    #define CONFIG_TMAP_PERIPHERAL_RIGHT TMAP_PERIPHERAL_RIGHT
#endif

//TMAP_PERIPHERAL_SET_RANK
#ifdef TMAP_PERIPHERAL_SET_RANK
    #define CONFIG_TMAP_PERIPHERAL_SET_RANK TMAP_PERIPHERAL_SET_RANK
#endif

//TMAP_PERIPHERAL_SINGLE
#ifdef TMAP_PERIPHERAL_SINGLE
    #define CONFIG_TMAP_PERIPHERAL_SINGLE TMAP_PERIPHERAL_SINGLE
#endif

//UTF8
#ifdef UTF8
    #define CONFIG_UTF8 UTF8
#endif

//ZBT
#ifdef ZBT
    #define CONFIG_ZBT ZBT
#endif

#endif
