from building import *

cwd = GetCurrentDir()

src = Glob('./*.c')
path =  [cwd, 
         os.path.join(cwd, '../include')]

group = DefineGroup('Drivers', src, depend = ['BSP_USING_BOARD_SF32LB52_LCD_N16R8_TEST'], CPPPATH = path)

if GetDepend('BSP_USING_BOARD_SF32LB52_LCD_N16R8_TEST'):
    group = group + SConscript('../sf32lb52-lcd_base_test/script/SConscript')

Return('group')
