from building import *
Import('rtconfig')

src   = []
CPPPATH = []
cwd   = GetCurrentDir()

CPPPATH += [cwd]

if GetDepend('CFG_BOOTLOADER'):
    src = []
else:
    src = ['efuse.c', "secboot.c"]

group = DefineGroup('boot', src, depend = ["USING_SECBOOT"],CPPPATH = CPPPATH)
    
Return('group')
