from building import *

cwd = GetCurrentDir()
src = ['bt_crypto.c']

if GetDepend("BT_USE_PSA_API"):
    src += ['bt_crypto_psa.c']
else:
    src += ['bt_crypto_tc.c']

CPPPATH = [cwd]

group = DefineGroup('zbt_crypto', src, depend = ['ZBT'],CPPPATH = CPPPATH)

Return('group')
